import Foundation

struct AnimationCodeGenerator {

    static func generate(config: SpriteAnimationConfig, mode: LanguageServerMode = .current) -> String {
        let module = luaIdent(config.moduleName.isEmpty ? "Animation" : config.moduleName)
        let frameSelectionEnum  = mode == .luaCATS ? "---@enum AnimationFrameSelectionMode\nlocal AnimationFrameSelectionMode = { range = \"range\", manual = \"manual\" }\n\n" : ""
        let classAnnotation     = mode == .luaCATS ? "---@class \(luaIdent(config.moduleName.isEmpty ? "Animation" : config.moduleName))\n" : ""
        let loadAnnotation      = mode == .luaCATS ? "---@return nil\n" : ""
        let newInstanceAnnot    = mode == .luaCATS ? "---@param animName string\n---@return {name:string,frame:integer,timer:number,playing:boolean,speed:number}\n" : ""
        let updateAnnotation    = mode == .luaCATS ? "---@param inst table\n---@param dt number\n---@param onEvent function?\n---@param onComplete function?\n---@param onLoop function?\n---@return nil\n" : ""
        let drawAnnotation      = mode == .luaCATS ? "---@param inst table\n---@param x number\n---@param y number\n---@param r number?\n---@param sx number?\n---@param sy number?\n---@param ox number?\n---@param oy number?\n---@return nil\n" : ""
        let playAnnotation      = mode == .luaCATS ? "---@param inst table\n---@return nil\n" : ""
        let pauseAnnotation     = mode == .luaCATS ? "---@param inst table\n---@return nil\n" : ""
        let stopAnnotation      = mode == .luaCATS ? "---@param inst table\n---@return nil\n" : ""
        let setAnimAnnotation   = mode == .luaCATS ? "---@param inst table\n---@param animName string\n---@return nil\n" : ""
        let setSpeedAnnotation  = mode == .luaCATS ? "---@param inst table\n---@param speed number\n---@return nil\n" : ""
        let getHitboxAnnot      = mode == .luaCATS ? "---@param inst table\n---@param label string?\n---@return {label:string,x:number,y:number,width:number,height:number}?\n" : ""
        let getHitboxWorldAnnot = mode == .luaCATS ? "---@param inst table\n---@param wx number\n---@param wy number\n---@param sx number?\n---@param sy number?\n---@param label string?\n---@return {label:string,x:number,y:number,width:number,height:number}?\n" : ""
        let getHitboxesAnnot    = mode == .luaCATS ? "---@param inst table\n---@return {label:string,x:number,y:number,width:number,height:number}[]\n" : ""
        let getHitboxesWAnnot   = mode == .luaCATS ? "---@param inst table\n---@param wx number\n---@param wy number\n---@param sx number?\n---@param sy number?\n---@return {label:string,x:number,y:number,width:number,height:number}[]\n" : ""
        let drawDebugAnnot      = mode == .luaCATS ? "---@param inst table\n---@param x number\n---@param y number\n---@param r number?\n---@param sx number?\n---@param sy number?\n---@return nil\n" : ""
        let getNamesAnnot       = mode == .luaCATS ? "---@return string[]\n" : ""
        let safeModulePath = safeLuaModuleName(config.moduleName)
        let path = config.spriteSheetPath.isEmpty ? "images/spritesheet.png" : config.spriteSheetPath
        let frameWidth = max(1, config.frameWidth)
        let frameHeight = max(1, config.frameHeight)
        let originX = config.centerOrigin ? "self.frameWidth / 2" : fmt2(config.offsetX)
        let originY = config.centerOrigin ? "self.frameHeight / 2" : fmt2(config.offsetY)
        let hasEvents = config.clips.contains { !$0.events.isEmpty }
        let animationTable = buildAnimationsTable(config)

        return """
--------------------------------------------------------------------------------
-- \(module).lua  ·  generated by LÖVE Studio
--------------------------------------------------------------------------------
--
-- SPRITE SHEET
--   Path      : \(path)
--   Frame     : \(frameWidth) × \(frameHeight) px
--   Clips     : \(config.clips.count)
--   Origin    : \(config.centerOrigin ? "center (frameWidth/2, frameHeight/2)" : "custom (\(fmt2(config.offsetX)), \(fmt2(config.offsetY)))")
--
-- HOW TO USE
-- ──────────
-- 1. Require this module at the top of the file that owns the entity:
--
--      local \(module) = require("animations/\(safeModulePath)")
--
-- 2. Load the sprite sheet once in love.load() - do this only once globally:
--
--      function love.load()
--          \(module):load()
--      end
--
-- 3. Create one instance per entity (each instance tracks its own frame/timer):
--
--      local player = \(module):newInstance("idle")
--
-- 4. Advance the animation every frame in love.update():
--
--      function love.update(dt)
--          \(module):update(player, dt, onAnimEvent)
--      end
--
-- 5. Draw the current frame in love.draw():
--
--      function love.draw()
--          \(module):draw(player, x, y)
--      end
--
-- 6. Switch to a different clip at any time (resets frame & timer):
--
--      \(module):setAnimation(player, "run")
--      \(module):setAnimation(player, "jump")
--
-- 7. Control playback speed (per-instance multiplier):
--
--      \(module):setSpeed(player, 2.0)   -- double speed
--      player.speed = 0.5               -- half speed (direct field access)
--
-- DEBUG HITBOXES
-- ──────────────
-- Enable hitbox rendering by setting the debug flag and calling drawDebug()
-- with the same position you pass to draw():
--
--      \(module).debug = true   -- toggle in love.load() or anywhere
--
--      function love.draw()
--          \(module):draw(player, x, y)
--          \(module):drawDebug(player, x, y)   -- draws on top
--      end
--
-- CALLBACKS
-- ─────────
-- Pass optional callbacks to update() for lifecycle events:
--
--      \(module):update(player, dt, onAnimEvent,
--          function(name) print("done:", name) end,    -- onComplete
--          function(name, n) print("loop", n) end      -- onLoop
--      )
--
-- HITBOXES
-- ────────
-- If hitboxes are defined in the editor they are exported per-clip per-frame.
-- Retrieve the hitbox (or all hitboxes) for the current frame at runtime:
--
--      local hb = \(module):getHitbox(player)
--      if hb then
--          -- hb.x, hb.y, hb.width, hb.height, hb.label
--      end
--
-- For collision checks, convert to world coordinates with scale:
--
--      local hb = \(module):getHitboxWorld(player, px, py, 3, 3)
--      if hb then
--          -- hb.x, hb.y, hb.width, hb.height are now in world pixels
--      end
--
--      local all = \(module):getHitboxes(player)
--
-- FRAME EVENTS
-- ────────────
-- Tag any frame in the Animation Editor with an event name (e.g. "footstep",
-- "hit", "spawn"). Pass a callback as the third argument to update() and it
-- will fire every time that frame is reached:
--
--      local function onAnimEvent(eventName, framePos, animName)
--          if eventName == "footstep" then
--              SoundManager:play("step")
--          elseif eventName == "hit" then
--              spawnHitEffect(player.x, player.y)
--          end
--      end
--
-- PER-FRAME DURATION
-- ──────────────────
-- Individual frames may carry a custom duration (seconds) that overrides the
-- clip fps for that frame only. Frames without a duration use 1/fps.
--------------------------------------------------------------------------------

\(frameSelectionEnum)\(classAnnotation)local \(module) = {}

\(module).imagePath = "\(path)"
\(module).image = nil
\(module).frameWidth = \(frameWidth)
\(module).frameHeight = \(frameHeight)
\(module).marginX = \(max(0, config.marginX))
\(module).marginY = \(max(0, config.marginY))
\(module).spacingX = \(max(0, config.spacingX))
\(module).spacingY = \(max(0, config.spacingY))

-- Set to true to draw hitboxes and origin crosshair via drawDebug()
\(module).debug = false

\(module).animations = {
\(animationTable)
}

local _quads = {}

local function frameKey(row, column)
    return tostring(row) .. ":" .. tostring(column)
end

local function buildRangeFrames(startRow, startColumn, frameCount, cols)
    local frames = {}
    local startIndex = (startRow - 1) * cols + (startColumn - 1)
    for i = 0, frameCount - 1 do
        local absolute = startIndex + i
        local column = (absolute % cols) + 1
        local row = math.floor(absolute / cols) + 1
        frames[#frames + 1] = { row = row, column = column }
    end
    return frames
end

-- Loads the sprite sheet image and builds all quad regions.
-- Call once in love.load() before creating any instances.
\(loadAnnotation)function \(module):load()
    self.image = love.graphics.newImage(self.imagePath)
    self.image:setFilter("nearest", "nearest")

    local imageWidth = self.image:getWidth()
    local imageHeight = self.image:getHeight()
    local cols = math.max(1, math.floor((imageWidth - self.marginX + self.spacingX) / (self.frameWidth + self.spacingX)))
    local rows = math.max(1, math.floor((imageHeight - self.marginY + self.spacingY) / (self.frameHeight + self.spacingY)))

    _quads = {}
    for row = 1, rows do
        for column = 1, cols do
            local x = self.marginX + (column - 1) * (self.frameWidth + self.spacingX)
            local y = self.marginY + (row - 1) * (self.frameHeight + self.spacingY)
            _quads[frameKey(row, column)] = love.graphics.newQuad(x, y, self.frameWidth, self.frameHeight, imageWidth, imageHeight)
        end
    end

    for name, anim in pairs(self.animations) do
        if anim.mode == "range" then
            anim.resolvedFrames = buildRangeFrames(anim.startRow, anim.startColumn, anim.frameCount, cols)
        else
            anim.resolvedFrames = anim.frames
        end
    end
end

-- Creates and returns a new animation instance starting on the given clip.
-- Each entity (player, enemy, etc.) needs its own instance.
--   animName : string  - name of the clip to start on (e.g. "idle")
-- Returns a table: { name, frame, timer, playing, speed }
\(newInstanceAnnot)function \(module):newInstance(animName)
    return { name = animName, frame = 1, timer = 0, playing = true, speed = 1.0 }
end

-- Advances the animation by dt seconds. Call every frame in love.update().
--   inst       : table     - instance returned by newInstance()
--   dt         : number    - delta time from love.update(dt)
--   onEvent    : function? - optional callback fired on tagged frames:
--                  onEvent(eventName, framePos, animName)
--   onComplete : function? - fired once when a non-looping animation finishes:
--                  onComplete(animName)
--   onLoop     : function? - fired each time a looping animation wraps:
--                  onLoop(animName, loopCount)
\(updateAnnotation)function \(module):update(inst, dt, onEvent, onComplete, onLoop)
    local anim = self.animations[inst.name]
    if not anim or not inst.playing then return end

    local frames = anim.resolvedFrames or anim.frames
    if not frames or #frames == 0 then return end

    local spd = (inst.speed or 1.0) * (anim.speed or 1.0)
    inst.timer = inst.timer + dt * math.max(0.001, spd)
    local defaultDur = 1 / math.max(anim.fps, 0.001)

    -- Advance through as many frames as dt covers (handles very low fps or
    -- large dt without skipping events). Each frame uses its own duration when
    -- set, otherwise falls back to the clip's fps.
    while true do
        local dur = (frames[inst.frame] and frames[inst.frame].duration) or defaultDur
        if inst.timer < dur then break end
        inst.timer = inst.timer - dur
        inst.frame = inst.frame + 1

        if inst.frame > #frames then
            if anim.loops then
                inst.frame = 1
                inst.loopCount = (inst.loopCount or 0) + 1
                if onLoop then onLoop(inst.name, inst.loopCount) end
            else
                inst.frame = #frames
                inst.playing = false
                if onComplete then onComplete(inst.name) end
                break
            end
        end

        if onEvent and anim.events and anim.events[inst.frame] then
            onEvent(anim.events[inst.frame], inst.frame, inst.name)
        end
    end
end

-- Draws the current frame of the instance at world position (x, y).
-- All parameters after y are optional and mirror love.graphics.draw().
--   inst : table   - instance returned by newInstance()
--   x, y : number  - world position
--   r    : number? - rotation in radians (default 0)
--   sx   : number? - horizontal scale   (default 1)
--   sy   : number? - vertical scale     (default sx)
--   ox   : number? - x origin offset    (default: module setting)
--   oy   : number? - y origin offset    (default: module setting)
\(drawAnnotation)function \(module):draw(inst, x, y, r, sx, sy, ox, oy)
    local anim = self.animations[inst.name]
    if not anim then return end

    local frames = anim.resolvedFrames or anim.frames
    if not frames or #frames == 0 then return end

    local frame = frames[inst.frame]
    if not frame then return end

    local quad = _quads[frameKey(frame.row, frame.column)]
    if not quad then return end

    local fsx = anim.flipH and -1 or 1
    local fsy = anim.flipV and -1 or 1
    local finalSx = (sx or 1) * fsx
    local finalSy = (sy or sx or 1) * fsy
    local finalOx = ox or \(originX)
    local finalOy = oy or \(originY)
    love.graphics.draw(self.image, quad, x or 0, y or 0, r or 0, finalSx, finalSy, finalOx, finalOy)
end

-- Resumes playback from the current frame.
--   inst : table - instance returned by newInstance()
\(playAnnotation)function \(module):play(inst)
    inst.playing = true
end

-- Pauses playback at the current frame without resetting it.
--   inst : table - instance returned by newInstance()
\(pauseAnnotation)function \(module):pause(inst)
    inst.playing = false
end

-- Stops playback and resets the instance back to frame 1.
--   inst : table - instance returned by newInstance()
\(stopAnnotation)function \(module):stop(inst)
    inst.playing = false
    inst.frame = 1
    inst.timer = 0
end

-- Switches the instance to a different clip and restarts it from frame 1.
-- Does nothing if the instance is already on that clip.
--   inst     : table  - instance returned by newInstance()
--   animName : string - name of the target clip (e.g. "run", "jump")
\(setAnimAnnotation)function \(module):setAnimation(inst, animName)
    if inst.name == animName then return end
    inst.name = animName
    inst.frame = 1
    inst.timer = 0
    inst.playing = true
    inst.loopCount = 0
end

-- Sets the playback speed multiplier for this instance.
-- Multiplies with the clip's own speed value.
--   inst  : table  - instance returned by newInstance()
--   speed : number - multiplier (1.0 = normal, 2.0 = double, 0.5 = half)
\(setSpeedAnnotation)function \(module):setSpeed(inst, speed)
    inst.speed = math.max(0, speed)
end

-- Returns the hitbox table for the current frame of the instance, or nil.
-- The returned table has: { label, x, y, width, height }
--   inst : table - instance returned by newInstance()
\(getHitboxAnnot)function \(module):getHitbox(inst, label)
    local anim = self.animations[inst.name]
    if not anim or not anim.hitboxes then return nil end
    local frameIdx = inst.frame  -- 1-based
    for _, hb in ipairs(anim.hitboxes) do
        if hb.frameIndex == frameIdx then
            if not label or hb.label == label then
                return hb
            end
        end
    end
    return nil
end

-- Returns the hitbox converted to world coordinates.
-- Applies entity position (wx, wy) and scale (sx, sy) so the result can be
-- passed directly to a collision check without extra math.
--   inst      : table  - instance returned by newInstance()
--   wx, wy    : number - world position of the entity (same as draw())
--   sx, sy    : number - scale of the entity (same as draw(), default 1)
--   label     : string? - filter by label (optional)
--
--   local hb = \(module):getHitboxWorld(p, x, y, 3, 3)
--   if hb and collidesWithMap(hb.x, hb.y, hb.width, hb.height) then ... end
\(getHitboxWorldAnnot)function \(module):getHitboxWorld(inst, wx, wy, sx, sy, label)
    local hb = self:getHitbox(inst, label)
    if not hb then return nil end
    local scaleX = sx or 1
    local scaleY = sy or sx or 1
    return {
        x      = (wx or 0) + hb.x * scaleX,
        y      = (wy or 0) + hb.y * scaleY,
        width  = hb.width  * math.abs(scaleX),
        height = hb.height * math.abs(scaleY),
        label  = hb.label,
    }
end

-- Returns all hitboxes for the current frame converted to world coordinates.
--   inst   : table  - instance returned by newInstance()
--   wx, wy : number - world position of the entity
--   sx, sy : number - scale of the entity (default 1)
--
--   local all = \(module):getHitboxesWorld(p, x, y, 3, 3)
\(getHitboxesWAnnot)function \(module):getHitboxesWorld(inst, wx, wy, sx, sy)
    local all = self:getHitboxes(inst)
    local scaleX = sx or 1
    local scaleY = sy or sx or 1
    local result = {}
    for _, hb in ipairs(all) do
        result[#result + 1] = {
            x      = (wx or 0) + hb.x * scaleX,
            y      = (wy or 0) + hb.y * scaleY,
            width  = hb.width  * math.abs(scaleX),
            height = hb.height * math.abs(scaleY),
            label  = hb.label,
        }
    end
    return result
end

-- Returns all hitboxes for the current frame as an array.
--   inst : table - instance returned by newInstance()
\(getHitboxesAnnot)function \(module):getHitboxes(inst)
    local anim = self.animations[inst.name]
    if not anim or not anim.hitboxes then return {} end
    local frameIdx = inst.frame
    local result = {}
    for _, hb in ipairs(anim.hitboxes) do
        if hb.frameIndex == frameIdx then
            result[#result + 1] = hb
        end
    end
    return result
end

-- Draws hitboxes for the current frame as coloured rectangles.
-- Call in love.draw() after draw() when \(module).debug is true.
--   inst  : table  - instance returned by newInstance()
--   x, y  : number - same world position passed to draw()
--   r, sx, sy : number? - same rotation/scale passed to draw() (default 0, 1, 1)
\(drawDebugAnnot)function \(module):drawDebug(inst, x, y, r, sx, sy)
    if not self.debug then return end
    local anim = self.animations[inst.name]
    if not anim then return end

    local frameIdx = inst.frame
    local scaleX = (sx or 1) * (anim.flipH and -1 or 1)
    local scaleY = (sy or sx or 1) * (anim.flipV and -1 or 1)
    local rot    = r or 0

    local prevR, prevG, prevB, prevA = love.graphics.getColor()
    local prevLW = love.graphics.getLineWidth()
    love.graphics.push("transform")
    love.graphics.translate(x or 0, y or 0)
    love.graphics.rotate(rot)
    love.graphics.scale(scaleX, scaleY)

    -- Draw hitboxes for current frame (shapes scale with sprite)
    local hitboxes = anim.hitboxes or {}
    local labels = {}  -- collect labels to draw after pop (unscaled)
    for i = 1, #hitboxes do
        local hb = hitboxes[i]
        if hb.frameIndex == frameIdx then
            love.graphics.setColor(0, 1, 0.2, 0.2)
            love.graphics.rectangle("fill", hb.x, hb.y, hb.width, hb.height)
            love.graphics.setColor(0, 1, 0.2, 1)
            love.graphics.setLineWidth(1)
            love.graphics.rectangle("line", hb.x, hb.y, hb.width, hb.height)
            if hb.label and hb.label ~= "" then
                -- transform the label position to world space for unscaled drawing
                local wx, wy = love.graphics.transformPoint(hb.x + 1, hb.y + 1)
                labels[#labels + 1] = { text = hb.label, x = wx, y = wy }
            end
        end
    end

    -- Origin crosshair (always shown when debug = true)
    love.graphics.setColor(1, 0.45, 0, 1)
    love.graphics.setLineWidth(1)
    love.graphics.line(-5, 0, 5, 0)
    love.graphics.line(0, -5, 0, 5)

    love.graphics.pop()

    -- Draw labels at world coords (no scale applied)
    love.graphics.setColor(0, 1, 0.2, 1)
    for i = 1, #labels do
        love.graphics.print(labels[i].text, labels[i].x, labels[i].y)
    end

    love.graphics.setColor(prevR, prevG, prevB, prevA)
    love.graphics.setLineWidth(prevLW)
end

-- Returns a sorted list of all clip names defined in this module.
-- Useful for debugging or building a UI picker.
\(getNamesAnnot)function \(module):getAnimationNames()
    local names = {}
    for name, _ in pairs(self.animations) do
        names[#names + 1] = name
    end
    table.sort(names)
    return names
end

return \(module)
"""
    }

    // MARK: - Animations table

    private static func buildAnimationsTable(_ config: SpriteAnimationConfig) -> String {
        let clips = config.clips.isEmpty ? [SpriteAnimationClip()] : config.clips
        return clips.map { clip in
            let key  = luaQuotedKey(clip.name.isEmpty ? "idle" : clip.name)
            let mode = clip.selectionMode == .range && clip.frames.isEmpty ? "range" : "manual"
            let frameBlock: String
            if mode == "range" {
                frameBlock = """
        startRow = \(max(1, clip.startRow)),
        startColumn = \(max(1, clip.startColumn)),
        frameCount = \(max(1, clip.frameCount)),
        frames = {},
"""
            } else {
                let unfolded = unfoldFrames(clip.frames)
                let frames = unfolded.isEmpty
                    ? "        frames = {},"
                    : "        frames = { " + unfolded.map { luaFrameLiteral($0) }.joined(separator: ", ") + " },"
                frameBlock = frames
            }

            let events: String
            if clip.events.isEmpty {
                events = "        events = {}"
            } else {
                let items = clip.events.map { event in
                    "[\(max(1, event.framePosition + 1))] = \"\(escapeLuaString(event.eventName))\""
                }.joined(separator: ", ")
                events = "        events = { \(items) }"
            }

            let speed = fmt2(max(0.01, clip.speed))
            let hitboxBlock = buildHitboxesBlock(clip.hitboxes)

            return """
    [\(key)] = {
        mode = "\(mode)",
\(frameBlock)
        fps = \(fmt2(max(0.001, clip.fps))),
        speed = \(speed),
        loops = \(clip.loops ? "true" : "false"),
        flipH = \(clip.flipH ? "true" : "false"),
        flipV = \(clip.flipV ? "true" : "false"),
\(events),
\(hitboxBlock)
    }
"""
        }.joined(separator: ",\n")
    }

    private static func buildHitboxesBlock(_ hitboxes: [FrameHitbox]) -> String {
        if hitboxes.isEmpty {
            return "        hitboxes = {}"
        }
        let items = hitboxes.map { hb in
            "{ frameIndex = \(max(1, hb.frameIndex + 1)), x = \(fmt2(hb.x)), y = \(fmt2(hb.y)), width = \(fmt2(hb.width)), height = \(fmt2(hb.height)), label = \"\(escapeLuaString(hb.label))\" }"
        }.joined(separator: ", ")
        return "        hitboxes = { \(items) }"
    }

    /// Expand each frame's repeatCount into multiple entries (repeat = 1 → no change).
    private static func unfoldFrames(_ frames: [SpriteAnimationFrameSelection]) -> [SpriteAnimationFrameSelection] {
        frames.flatMap { f -> [SpriteAnimationFrameSelection] in
            let count = max(1, f.repeatCount)
            return (0..<count).map { _ in
                SpriteAnimationFrameSelection(row: f.row, column: f.column, duration: f.duration)
            }
        }
    }

    /// Emit a Lua frame literal, adding `duration` only when explicitly set.
    private static func luaFrameLiteral(_ f: SpriteAnimationFrameSelection) -> String {
        var parts = "{ row = \(max(1, f.row)), column = \(max(1, f.column))"
        if let dur = f.duration {
            parts += ", duration = \(String(format: "%.4f", max(0.001, dur)))"
        }
        parts += " }"
        return parts
    }

    // MARK: - Helpers

    private static func luaQuotedKey(_ value: String) -> String {
        "\"\(escapeLuaString(value))\""
    }

    private static func escapeLuaString(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }

    private static func fmt2(_ value: Double) -> String {
        String(format: "%.2f", value)
    }

    private static func luaIdent(_ name: String) -> String {
        let safe = name
            .components(separatedBy: CharacterSet.alphanumerics.union(.init(charactersIn: "_")).inverted)
            .joined(separator: "_")
            .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        let result = safe.isEmpty ? "animation" : safe
        return result.first?.isNumber == true ? "_\(result)" : result
    }

    private static func safeLuaModuleName(_ name: String) -> String {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let safe = trimmed
            .components(separatedBy: CharacterSet.alphanumerics.union(.init(charactersIn: "_-")).inverted)
            .joined(separator: "_")
        return safe.isEmpty ? "animation" : safe
    }
}
