import Foundation

struct CameraCodeGenerator {

    static func generate(config: CameraConfig) -> String {
        let mod  = luaIdent(config.moduleName.isEmpty ? "Camera" : config.moduleName)
        let lerp = fmt(config.lerpSpeed)
        let zlerp = fmt(config.zoomLerpSpeed)
        let zoom = fmt(config.defaultZoom)
        let decay = fmt(config.shakeDecay)
        let shakeInt = fmt(config.shakeIntensity)
        let round = config.roundPixels ? "true" : "false"

        // Deadzone block
        let deadzoneInit: String
        let deadzoneUpdate: String
        if config.deadzoneEnabled {
            let dw = fmt(config.deadzoneW / 2)
            let dh = fmt(config.deadzoneH / 2)
            deadzoneInit = "    self._dzW, self._dzH = \(fmt(config.deadzoneW)), \(fmt(config.deadzoneH))"
            deadzoneUpdate = """
    -- Deadzone: only move target when object leaves the box
    local dx = obj.x - self.tx
    local dy = obj.y - self.ty
    if dx >  \(dw) then self.tx = obj.x - \(dw) end
    if dx < -\(dw) then self.tx = obj.x + \(dw) end
    if dy >  \(dh) then self.ty = obj.y - \(dh) end
    if dy < -\(dh) then self.ty = obj.y + \(dh) end
"""
        } else {
            deadzoneInit = ""
            deadzoneUpdate = "    self.tx, self.ty = obj.x, obj.y"
        }

        // Bounds block
        let boundsInit: String
        let boundsClamp: String
        if config.boundsEnabled {
            boundsInit = "    self._bounds = { x=\(fmt(config.boundsX)), y=\(fmt(config.boundsY)), w=\(fmt(config.boundsW)), h=\(fmt(config.boundsH)) }"
            boundsClamp = """

    -- Clamp to world bounds
    if self._bounds then
        local sw, sh = love.graphics.getDimensions()
        local hw, hh = sw * 0.5 / self.zoom, sh * 0.5 / self.zoom
        self.x = math.max(self._bounds.x + hw, math.min(self._bounds.x + self._bounds.w - hw, self.x))
        self.y = math.max(self._bounds.y + hh, math.min(self._bounds.y + self._bounds.h - hh, self.y))
    end
"""
        } else {
            boundsInit   = ""
            boundsClamp  = ""
        }

        let boundsDoc: String
        if config.boundsEnabled {
            boundsDoc = """
--
-- WORLD BOUNDS  (\(Int(config.boundsX)), \(Int(config.boundsY)))  \(Int(config.boundsW)) × \(Int(config.boundsH)) px
-- Camera will never show outside this rectangle.
"""
        } else {
            boundsDoc = "--\n-- World bounds: disabled"
        }

        let deadzoneDoc = config.deadzoneEnabled
            ? "--\n-- Deadzone: \(Int(config.deadzoneW)) × \(Int(config.deadzoneH)) px  (camera leads when target leaves box)"
            : "--\n-- Deadzone: disabled"

        return """
--------------------------------------------------------------------------------
-- \(mod).lua
-- Generated by LÖVE Studio · Camera Config
--------------------------------------------------------------------------------
--
-- QUICK START
-- -----------
-- 1. Require at the top of main.lua:
--
--      local \(mod) = require("\(mod.lowercased())")
--
-- 2. Create a camera instance in love.load():
--
--      function love.load()
--          cam = \(mod).new()
--      end
--
-- 3. Update each frame and wrap your draw calls:
--
--      function love.update(dt)
--          cam:follow(player.x, player.y)
--          cam:update(dt)
--      end
--
--      function love.draw()
--          cam:attach()
--              -- draw world here
--          cam:detach()
--          -- draw HUD here (not affected by camera)
--      end
--
-- 4. Trigger a screen shake:
--
--      cam:shake(\(shakeInt))          -- uses default intensity
--      cam:shake(20, 0.5)   -- intensity=20, custom decay
--
-- 5. Zoom in/out (smooth):
--
--      cam:setZoom(2.0)     -- zoom to 2×
--      cam:setZoom(1.0)     -- back to normal
--
-- 6. Convert coordinates:
--
--      local wx, wy = cam:toWorld(love.mouse.getPosition())   -- screen → world
--      local sx, sy = cam:toScreen(enemy.x, enemy.y)         -- world → screen
--
\(deadzoneDoc)
\(boundsDoc)
--
-- CONFIG
--   lerp speed   : \(lerp)   (0.01 = very slow, 1.0 = instant snap)
--   zoom lerp    : \(zlerp)
--   default zoom : \(zoom)
--   shake decay  : \(decay)   (per frame, 0.80 = fast fade, 0.99 = long tail)
--   round pixels : \(round)
--------------------------------------------------------------------------------

local \(mod) = {}
\(mod).__index = \(mod)

-- ── Internal config ───────────────────────────────────────────────────────
local LERP         = \(lerp)
local ZOOM_LERP    = \(zlerp)
local SHAKE_DECAY  = \(decay)
local ROUND_PIXELS = \(round)

--------------------------------------------------------------------------------
-- \(mod).new(x, y) → camera
-- Create a new camera, optionally pre-positioned at world coords (x, y).
--------------------------------------------------------------------------------
function \(mod).new(x, y)
    local self = setmetatable({}, \(mod))
    self.x, self.y   = x or 0, y or 0
    self.tx, self.ty = self.x, self.y
    self.zoom        = \(zoom)
    self.targetZoom  = \(zoom)
    self.rotation    = 0
    self._shakeMag   = 0
    self._shakeX     = 0
    self._shakeY     = 0
\(boundsInit)\(deadzoneInit)
    return self
end

--------------------------------------------------------------------------------
-- cam:follow(obj)  or  cam:follow(x, y)
-- Set the follow target. Pass a table with .x/.y or two numbers.
--------------------------------------------------------------------------------
function \(mod):follow(obj, y)
    if type(obj) == "number" then
        obj = { x = obj, y = y }
    end
\(deadzoneUpdate)
end

--------------------------------------------------------------------------------
-- cam:update(dt)
-- Call once per frame in love.update(dt).
--------------------------------------------------------------------------------
function \(mod):update(dt)
    -- Lerp position toward target
    self.x = self.x + (self.tx - self.x) * LERP
    self.y = self.y + (self.ty - self.y) * LERP
    if ROUND_PIXELS then
        self.x = math.floor(self.x + 0.5)
        self.y = math.floor(self.y + 0.5)
    end

    -- Smooth zoom
    self.zoom = self.zoom + (self.targetZoom - self.zoom) * ZOOM_LERP
\(boundsClamp)
    -- Screen shake
    if self._shakeMag > 0.5 then
        self._shakeX = (math.random() * 2 - 1) * self._shakeMag
        self._shakeY = (math.random() * 2 - 1) * self._shakeMag
        self._shakeMag = self._shakeMag * SHAKE_DECAY
    else
        self._shakeMag = 0
        self._shakeX, self._shakeY = 0, 0
    end
end

--------------------------------------------------------------------------------
-- cam:attach()   - call before drawing the world
-- cam:detach()   - call after drawing the world
--------------------------------------------------------------------------------
function \(mod):attach()
    -- Use canvas dimensions when drawing to a virtual canvas (e.g. Resolution module),
    -- otherwise fall back to the real window size.
    local canvas = love.graphics.getCanvas()
    local sw, sh
    if canvas then
        sw, sh = canvas:getDimensions()
    else
        sw, sh = love.graphics.getDimensions()
    end
    love.graphics.push()
    love.graphics.translate(sw * 0.5 + self._shakeX, sh * 0.5 + self._shakeY)
    love.graphics.scale(self.zoom)
    love.graphics.rotate(self.rotation)
    love.graphics.translate(-self.x, -self.y)
end

function \(mod):detach()
    love.graphics.pop()
end

--------------------------------------------------------------------------------
-- cam:shake(intensity)
-- Trigger a screen shake. intensity = max pixel offset (default \(shakeInt)).
--------------------------------------------------------------------------------
function \(mod):shake(intensity)
    self._shakeMag = intensity or \(shakeInt)
end

--------------------------------------------------------------------------------
-- cam:setZoom(z)
-- Smoothly zoom to level z (1.0 = normal, 2.0 = 2×, 0.5 = half).
--------------------------------------------------------------------------------
function \(mod):setZoom(z)
    self.targetZoom = math.max(0.1, z)
end

--------------------------------------------------------------------------------
-- cam:snapTo(x, y)
-- Instantly move camera to world position - no lerp.
--------------------------------------------------------------------------------
function \(mod):snapTo(x, y)
    self.x, self.y   = x, y
    self.tx, self.ty = x, y
end

--------------------------------------------------------------------------------
-- cam:toWorld(sx, sy) → wx, wy
-- Convert screen coordinates to world coordinates.
--------------------------------------------------------------------------------
function \(mod):toWorld(sx, sy)
    local sw, sh = love.graphics.getDimensions()
    local wx = (sx - sw * 0.5) / self.zoom + self.x
    local wy = (sy - sh * 0.5) / self.zoom + self.y
    return wx, wy
end

--------------------------------------------------------------------------------
-- cam:toScreen(wx, wy) → sx, sy
-- Convert world coordinates to screen coordinates.
--------------------------------------------------------------------------------
function \(mod):toScreen(wx, wy)
    local sw, sh = love.graphics.getDimensions()
    local sx = (wx - self.x) * self.zoom + sw * 0.5
    local sy = (wy - self.y) * self.zoom + sh * 0.5
    return sx, sy
end

return \(mod)
"""
    }

    // MARK: - Helpers

    private static func fmt(_ v: Double) -> String { String(format: "%.2f", v) }

    private static func luaIdent(_ name: String) -> String {
        let safe = name
            .components(separatedBy: CharacterSet.alphanumerics.union(.init(charactersIn: "_")).inverted)
            .joined(separator: "_")
            .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        let result = safe.isEmpty ? "Camera" : safe
        return result.first?.isNumber == true ? "_\(result)" : result
    }
}
