import Foundation

struct FontCodeGenerator {

    static func generate(config: FontManagerConfig, mode: LanguageServerMode = .current) -> String {
        let mod = luaIdent(config.moduleName.isEmpty ? "Fonts" : config.moduleName)
        let fontSourceEnum    = mode == .luaCATS ? "---@enum FontSource\nlocal FontSource = { default = \"default\", file = \"file\", imageFont = \"imageFont\" }\n\n" : ""
        let classAnnotation   = mode == .luaCATS ? "---@class \(luaIdent(config.moduleName.isEmpty ? "Fonts" : config.moduleName))\n" : ""
        let loadAnnotation    = mode == .luaCATS ? "---@return nil\n" : ""
        let getAnnotation     = mode == .luaCATS ? "---@param name string\n---@return love.Font?\n" : ""
        let setAnnotation     = mode == .luaCATS ? "---@param name string\n---@return nil\n" : ""
        let restoreAnnotation = mode == .luaCATS ? "---@return nil\n" : ""
        let printAnnotation   = mode == .luaCATS ? "---@param name string\n---@param text string\n---@param x number\n---@param y number\n---@return nil\n" : ""
        let printfAnnotation  = mode == .luaCATS ? "---@param name string\n---@param text string\n---@param x number\n---@param y number\n---@param limit number\n---@param align string?\n---@return nil\n" : ""
        let widthAnnotation   = mode == .luaCATS ? "---@param name string\n---@param text string\n---@return number\n" : ""
        let heightAnnotation  = mode == .luaCATS ? "---@param name string\n---@return number\n" : ""
        let unloadAnnotation  = mode == .luaCATS ? "---@return nil\n" : ""

        // Load lines - one per entry
        let loadLines = config.entries.map { e -> String in
            let key = luaIdent(e.name)
            switch e.source {
            case .default:
                return "    _fonts.\(key) = love.graphics.newFont(\(e.size))"
            case .file:
                let path = e.filePath.isEmpty ? "fonts/\(e.name).ttf" : e.filePath
                return """
    if love.filesystem.getInfo("\(path)") then
        _fonts.\(key) = love.graphics.newFont("\(path)", \(e.size))
    else
        print("[Fonts] WARNING: '\(path)' not found - falling back to default size \(e.fallback)")
        _fonts.\(key) = love.graphics.newFont(\(e.fallback))
    end
"""
            case .imageFont:
                let path = e.filePath.isEmpty ? "fonts/\(e.name).png" : e.filePath
                let glyphs = e.glyphs.isEmpty ? " ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789" : e.glyphs
                return "    _fonts.\(key) = love.graphics.newImageFont(\"\(path)\", \"\(glyphs)\")"
            }
        }.joined(separator: "\n")

        // Font list comment
        let fontList = config.entries.map { e -> String in
            let key = luaIdent(e.name)
            let padded = key.padding(toLength: 20, withPad: " ", startingAt: 0)
            switch e.source {
            case .default:
                return "--   \(padded)  \(e.size)px  [default]"
            case .file:
                let path = e.filePath.isEmpty ? "fonts/\(e.name).ttf" : e.filePath
                return "--   \(padded)  \(e.size)px  \(path)"
            case .imageFont:
                let path = e.filePath.isEmpty ? "fonts/\(e.name).png" : e.filePath
                return "--   \(padded)  image font  \(path)"
            }
        }.joined(separator: "\n")

        let firstKey = config.entries.first.map { luaIdent($0.name) } ?? "title"

        // Outline table lines - only for entries that have outline enabled
        let outlineLines = config.entries
            .filter { $0.outlineEnabled }
            .map { e -> String in
                let key = luaIdent(e.name)
                let r = String(format: "%.3f", Double(e.outlineR) / 255.0)
                let g = String(format: "%.3f", Double(e.outlineG) / 255.0)
                let b = String(format: "%.3f", Double(e.outlineB) / 255.0)
                let a = String(format: "%.3f", Double(e.outlineA) / 255.0)
                return "    _outlines.\(key) = { size = \(e.outlineSize), r = \(r), g = \(g), b = \(b), a = \(a) }"
            }
            .joined(separator: "\n")

        return """
--------------------------------------------------------------------------------
-- \(mod).lua
-- Generated by LÖVE Studio · Font Manager
--------------------------------------------------------------------------------
--
-- QUICK START
-- -----------
-- 1. Require at the top of main.lua:
--
--      local \(mod) = require("\(mod.lowercased())")
--
-- 2. Load all fonts in love.load():
--
--      function love.load()
--          \(mod):load()
--      end
--
-- 3. Draw text with a named font:
--
--      \(mod):print("\(firstKey)", "Hello world!", x, y)
--      \(mod):printf("\(firstKey)", "Centered text", x, y, width, "center")
--
-- 4. Set a font as the active LÖVE font (then use love.graphics.print normally):
--
--      \(mod):set("\(firstKey)")
--      love.graphics.print("Hello!", x, y)
--      \(mod):restore()   -- restores font that was active before set()
--
-- 5. Get a font object directly:
--
--      local f = \(mod):get("\(firstKey)")
--      local textW = f:getWidth("Score: 100")
--
-- FONTS  (\(config.entries.count) configured)
-- -------------------------------------------------------
\(fontList.isEmpty ? "--   (none)" : fontList)
-- -------------------------------------------------------
--------------------------------------------------------------------------------

\(fontSourceEnum)\(classAnnotation)local \(mod) = {}

local _fonts    = {}
local _outlines = {}
local _prevFont = nil

--------------------------------------------------------------------------------
-- \(mod):load()
-- Call once in love.load(). Loads all font files from disk.
--------------------------------------------------------------------------------
\(loadAnnotation)function \(mod):load()
\(loadLines.isEmpty ? "    -- No fonts configured." : loadLines)
\(outlineLines.isEmpty ? "" : "\n    -- Outline data\n" + outlineLines)
end

--------------------------------------------------------------------------------
-- \(mod):get(name) → Font | nil
-- Returns the Font object for the given name, or nil if not loaded.
--------------------------------------------------------------------------------
\(getAnnotation)function \(mod):get(name)
    return _fonts[name]
end

--------------------------------------------------------------------------------
-- \(mod):set(name)
-- Sets the named font as the active LÖVE font.
-- Saves the previously active font so it can be restored with :restore().
--------------------------------------------------------------------------------
\(setAnnotation)function \(mod):set(name)
    local f = _fonts[name]
    if f then
        _prevFont = love.graphics.getFont()
        love.graphics.setFont(f)
    else
        print("[Fonts] WARNING: font '" .. name .. "' not loaded.")
    end
end

--------------------------------------------------------------------------------
-- \(mod):restore()
-- Restores the font that was active before the last :set() call.
--------------------------------------------------------------------------------
\(restoreAnnotation)function \(mod):restore()
    if _prevFont then
        love.graphics.setFont(_prevFont)
        _prevFont = nil
    end
end

--------------------------------------------------------------------------------
-- \(mod):print(name, text, x, y [, r, sx, sy, ox, oy, kx, ky])
-- Draws text using the named font, with outline if configured.
--------------------------------------------------------------------------------
\(printAnnotation)function \(mod):print(name, text, x, y, r, sx, sy, ox, oy, kx, ky)
    local ol = _outlines[name]
    if ol then
        local cr, cg, cb, ca = love.graphics.getColor()
        love.graphics.setColor(ol.r, ol.g, ol.b, ol.a)
        self:set(name)
        local s = ol.size
        for dx = -s, s do
            for dy = -s, s do
                if dx ~= 0 or dy ~= 0 then
                    love.graphics.print(text, x + dx, y + dy, r or 0, sx or 1, sy or 1, ox or 0, oy or 0, kx or 0, ky or 0)
                end
            end
        end
        love.graphics.setColor(cr, cg, cb, ca)
    end
    self:set(name)
    love.graphics.print(text, x, y, r or 0, sx or 1, sy or 1, ox or 0, oy or 0, kx or 0, ky or 0)
    self:restore()
end

--------------------------------------------------------------------------------
-- \(mod):printf(name, text, x, y, limit [, align])
-- Draws wrapped/aligned text using the named font, with outline if configured.
-- align: "left" | "center" | "right" | "justify"  (default "left")
--------------------------------------------------------------------------------
\(printfAnnotation)function \(mod):printf(name, text, x, y, limit, align)
    local ol = _outlines[name]
    if ol then
        local cr, cg, cb, ca = love.graphics.getColor()
        love.graphics.setColor(ol.r, ol.g, ol.b, ol.a)
        self:set(name)
        local s = ol.size
        for dx = -s, s do
            for dy = -s, s do
                if dx ~= 0 or dy ~= 0 then
                    love.graphics.printf(text, x + dx, y + dy, limit, align or "left")
                end
            end
        end
        love.graphics.setColor(cr, cg, cb, ca)
    end
    self:set(name)
    love.graphics.printf(text, x, y, limit, align or "left")
    self:restore()
end

--------------------------------------------------------------------------------
-- \(mod):getWidth(name, text) → number
-- Returns the pixel width of text rendered with the named font.
--------------------------------------------------------------------------------
\(widthAnnotation)function \(mod):getWidth(name, text)
    local f = _fonts[name]
    return f and f:getWidth(text) or 0
end

--------------------------------------------------------------------------------
-- \(mod):getHeight(name) → number
-- Returns the line height of the named font in pixels.
--------------------------------------------------------------------------------
\(heightAnnotation)function \(mod):getHeight(name)
    local f = _fonts[name]
    return f and f:getHeight() or 0
end

--------------------------------------------------------------------------------
-- \(mod):unload()
-- Releases all font objects (frees GPU memory).
--------------------------------------------------------------------------------
\(unloadAnnotation)function \(mod):unload()
    _fonts = {}
end

return \(mod)
"""
    }

    static func luaIdent(_ name: String) -> String {
        let safe = name
            .components(separatedBy: CharacterSet.alphanumerics.union(.init(charactersIn: "_")).inverted)
            .joined(separator: "_")
            .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        let result = safe.isEmpty ? "font" : safe
        return result.first?.isNumber == true ? "_\(result)" : result
    }
}
