import Foundation

struct ParticleCodeGenerator {

    static func generate(config: ParticleSystemConfig) -> String {
        let ident      = luaIdent(config.name)
        // LÖVE setSpread() takes the full cone angle; the preview uses ±spreadDeg
        // (half-angle), so multiply by 2 to match visual output.
        let spreadRad  = fmt4(config.spreadDeg * 2  * .pi / 180.0)
        let dirRad     = fmt4(-config.directionDeg  * .pi / 180.0)
        let rotMin     = fmt4(config.rotationMinDeg * .pi / 180.0)
        let rotMax     = fmt4(config.rotationMaxDeg * .pi / 180.0)
        let rsMin      = fmt4(config.rotSpeedMinDeg * .pi / 180.0)
        let rsMax      = fmt4(config.rotSpeedMaxDeg * .pi / 180.0)

        let sr = fmt2(config.colorStartR); let sg = fmt2(config.colorStartG)
        let sb = fmt2(config.colorStartB); let sa = fmt2(config.colorStartA)
        let er = fmt2(config.colorEndR);   let eg = fmt2(config.colorEndG)
        let eb = fmt2(config.colorEndB);   let ea = fmt2(config.colorEndA)

        // Canvas size for the procedural soft circle.
        // 64×64 gives enough resolution so particles stay smooth at any scale.
        let canvasSize = 64
        let canvasHalf = canvasSize / 2

        let hasCustomTexture = config.textureName != nil && !config.textureName!.isEmpty
        let sizeStartPx = Int(config.sizeStart)
        let sizeEndPx   = Int(config.sizeEnd)
        // Used only for the default canvas path:
        let sizeScale = 1.0 / Double(canvasSize)
        let sS = fmt3(config.sizeStart * sizeScale)
        let eS = fmt3(config.sizeEnd   * sizeScale)

        let textureBlock: String
        if let name = config.textureName, !name.isEmpty {
            textureBlock = """
        _texture = love.graphics.newImage("\(name)")
        _texture:setFilter("linear", "linear")
    """
        } else {
            let shapeCode = canvasShapeCode(config.shape, size: canvasSize)
            textureBlock =
                "    -- Procedural \(config.shape.displayName) canvas (\(canvasSize)×\(canvasSize) px).\n" +
                "    -- Replace with love.graphics.newImage(\"path/to/img.png\") for a custom sprite.\n" +
                "    local canvas = love.graphics.newCanvas(\(canvasSize), \(canvasSize))\n" +
                "    love.graphics.setCanvas(canvas)\n" +
                "    love.graphics.clear(0, 0, 0, 0)\n" +
                // "replace" stores pixels as straight alpha (not premultiplied).
                // This lets "add" (alphamultiply) correctly apply particle alpha for fading,
                // and avoids double-alpha on antialiased edges in LÖVE 11+ canvases.
                "    love.graphics.setBlendMode(\"replace\")\n" +
                "    love.graphics.setColor(1, 1, 1, 1)\n" +
                shapeCode + "\n" +
                "    love.graphics.setBlendMode(\"alpha\")\n" +
                "    love.graphics.setCanvas()\n" +
                "    love.graphics.setColor(1, 1, 1, 1)\n" +
                "    canvas:setFilter(\"linear\", \"linear\")\n" +
                "    _texture = canvas"
        }

        let emissionBlock: String
        if config.isBurst {
            emissionBlock = """
        -- Burst mode: fire \(config.burstCount) particles at once, then stop.
        -- Call M:burst() to replay it.
        _ps:setEmissionRate(0)
        _ps:emit(\(config.burstCount))
    """
        } else {
            emissionBlock = "    _ps:setEmissionRate(\(Int(config.emissionRate)))"
        }

        let areaSpreadLine = config.emitterRadius > 0
            ? "\n    _ps:setEmissionArea(\"uniform\", \(fmt2(config.emitterRadius)), \(fmt2(config.emitterRadius)))"
            : ""

        let burstHelpers = config.isBurst ? """


--------------------------------------------------------------------------------
-- \(ident):burst(x, y)
-- Fires a burst of \(config.burstCount) particles at world position (x, y).
-- Old particles are NOT cleared - they finish their lifetime naturally.
-- Call as many times as needed (e.g. on impact, explosion, button press).
--   x, y  (optional) - world position; omit to reuse the last known position.
--------------------------------------------------------------------------------
function \(ident):burst(x, y)
    if x and y then _ps:setPosition(x, y) end
    _ps:emit(\(config.burstCount))
end
""" : ""

        return """
--------------------------------------------------------------------------------
-- \(config.name).lua  ·  generated by LÖVE Studio
--------------------------------------------------------------------------------
--
-- PARTICLE INFO
--   Mode      : \(config.isBurst ? "Burst (\(config.burstCount) particles, one-shot)" : "Continuous (\(Int(config.emissionRate)) particles/s)")
--   Max       : \(config.maxParticles) particles
--   Lifetime  : \(fmt2(config.lifetimeMin))s – \(fmt2(config.lifetimeMax))s
--   Speed     : \(Int(config.speedMin)) – \(Int(config.speedMax)) px/s
--   Direction : \(Int(config.directionDeg))° ± \(Int(config.spreadDeg))° spread
--   Gravity   : (\(Int(config.gravityX)), \(Int(config.gravityY))) px/s²
--   Size      : \(Int(config.sizeStart))px → \(Int(config.sizeEnd))px
--   Texture   : \(config.textureName ?? "procedural \(config.shape.displayName) (64×64 canvas)")
--   Blend     : \(config.blendMode.rawValue)
--
-- HOW TO USE
-- ──────────
-- 1. Require this module wherever you need the effect:
--
--      local \(luaIdent(config.name)) = require("particles/\(config.name)")
--
-- 2. Load assets once in love.load() - creates the texture and particle system:
--
--      function love.load()
--          \(luaIdent(config.name)):load()
--      end
--
-- 3. Advance particles every frame in love.update():
--
--      function love.update(dt)
--          local x, y = love.mouse.getPosition()
--          \(luaIdent(config.name)):update(dt, x, y)   -- moves emitter, not living particles
--      end
--
-- 4. Draw in love.draw() - no position needed here:
--
--      function love.draw()
--          \(luaIdent(config.name)):draw()
--      end
--\(config.isBurst ? """

-- 5. Replay the burst at a world position (e.g. on impact, explosion):
--
--      \(luaIdent(config.name)):burst(x, y)
--
-- BURST MODE
-- ──────────
-- This effect is one-shot. After :load() it fires once automatically.
-- Call :burst(x, y) to replay it at any position as many times as needed.
-- Old particles are NOT cleared - they finish their lifetime naturally.
-- Use :isActive() to detect when all particles have faded out:
--
--      if not \(luaIdent(config.name)):isActive() then
--          -- effect finished, do something
--      end
--
""" : "")
-- LIFECYCLE
-- ─────────
--   :load()          - create resources, call once in love.load()
--   :update(dt,x,y)  - advance simulation + move emitter to (x,y)
--   :draw()          - render all living particles at their world positions
--   :stop()          - stop emitting (living particles finish naturally)
--   :unload()        - release GPU resources when no longer needed
--------------------------------------------------------------------------------

local \(ident) = {}

-- Internal state - do not access directly from outside this module
local _ps      = nil   -- love.graphics.ParticleSystem
local _texture = nil   -- love.graphics.Image (or Canvas)

--------------------------------------------------------------------------------
-- \(ident):load()
-- Creates the texture and particle system. Must be called once before any other
-- method, typically inside love.load().
--------------------------------------------------------------------------------
function \(ident):load()
\(textureBlock)

    _ps = love.graphics.newParticleSystem(_texture, \(config.maxParticles))

\(emissionBlock)

    -- How long each particle lives (seconds)
    _ps:setParticleLifetime(\(fmt2(config.lifetimeMin)), \(fmt2(config.lifetimeMax)))

    -- Initial speed range (pixels per second)
    _ps:setSpeed(\(fmt2(config.speedMin)), \(fmt2(config.speedMax)))

    -- Direction: \(Int(config.directionDeg))° (\(directionLabel(config.directionDeg))) ± \(Int(config.spreadDeg))° spread
    -- LÖVE uses radians, measured clockwise from the right (east) axis.
    _ps:setDirection(\(dirRad))
    _ps:setSpread(\(spreadRad))

    -- Gravity / linear acceleration (px/s²). Positive Y = downward on screen.
    _ps:setLinearAcceleration(
        \(fmt2(config.gravityX)), \(fmt2(config.gravityY)),
        \(fmt2(config.gravityX)), \(fmt2(config.gravityY))
    )

    -- Particle size: setSizes() is a scale factor relative to the texture size.
    -- We divide the desired pixel size by the texture width so the result is
    -- correct regardless of the source image dimensions.
\(hasCustomTexture ? """
    local _tw = _texture:getWidth()
    _ps:setSizes(\(sizeStartPx) / _tw, \(sizeEndPx) / _tw)
""" : """
    -- Procedural canvas is 16×16 px, so \(sS) ≈ \(sizeStartPx)px and \(eS) ≈ \(sizeEndPx)px.
    _ps:setSizes(\(sS), \(eS))
""")

    -- Color gradient from start to end (R, G, B, A each 0–1)
    _ps:setColors(
        \(sr), \(sg), \(sb), \(sa),   -- start: rgba
        \(er), \(eg), \(eb), \(ea)    -- end:   rgba
    )

    -- Rotation at spawn (radians). \(Int(config.rotationMinDeg))° – \(Int(config.rotationMaxDeg))°.
    _ps:setRotation(\(rotMin), \(rotMax))

    -- Angular velocity (radians/s). \(Int(config.rotSpeedMinDeg))°/s – \(Int(config.rotSpeedMaxDeg))°/s.
    _ps:setSpin(\(rsMin), \(rsMax))
    _ps:setSpinVariation(1)\(areaSpreadLine)\(config.sizeVariation > 0 ? "\n    _ps:setSizeVariation(\(fmt2(config.sizeVariation)))" : "")\(config.damping > 0 ? "\n    _ps:setLinearDamping(0, \(fmt2(config.damping)))" : "")

    _ps:start()
end

--------------------------------------------------------------------------------
-- \(ident):update(dt, x, y)
-- Advances all living particles by dt seconds.
-- Pass (x, y) to move the emitter - new particles will spawn there while
-- already-living particles keep their own world positions (trailing effect).
-- Call every frame from love.update(dt).
--------------------------------------------------------------------------------
function \(ident):update(dt, x, y)
    if not _ps then return end
    if x and y then
        _ps:setPosition(x, y)
    end
    _ps:update(dt)
end

--------------------------------------------------------------------------------
-- \(ident):draw()
-- Draws all living particles at their world positions.
-- Do NOT pass an offset here - positions are already in world space because
-- the emitter was moved via :update(dt, x, y).
--------------------------------------------------------------------------------
function \(ident):draw()
    if not _ps then return end
    local r, g, b, a = love.graphics.getColor()
\(config.blendMode == .additive ? """
    local prevBlend, prevAlphaMode = love.graphics.getBlendMode()
    -- "alphamultiply" (default): dst += src_rgb * particle_alpha.
    -- The canvas was drawn with "replace" so it holds straight alpha - correct.
    love.graphics.setBlendMode("add", "alphamultiply")
""" : "")    love.graphics.setColor(1, 1, 1, 1)
    love.graphics.draw(_ps, 0, 0)
\(config.blendMode != .alpha ? """
    love.graphics.setBlendMode(prevBlend, prevAlphaMode)
""" : "")    love.graphics.setColor(r, g, b, a)
end

--------------------------------------------------------------------------------
-- \(ident):isActive() → boolean
-- Returns true while particles are still alive (useful for one-shot bursts to
-- know when the effect has fully finished).
--------------------------------------------------------------------------------
function \(ident):isActive()
    return _ps ~= nil and (_ps:getCount() > 0 or _ps:isActive())
end

--------------------------------------------------------------------------------
-- \(ident):stop()
-- Stops emitting new particles. Already-living particles finish their lifetime.
-- Call \(ident):load() again to restart from scratch.
--------------------------------------------------------------------------------
function \(ident):stop()
    if _ps then _ps:stop() end
end

--------------------------------------------------------------------------------
-- \(ident):unload()
-- Releases GPU resources. Call when the effect is no longer needed.
--------------------------------------------------------------------------------
function \(ident):unload()
    if _ps      then _ps:release();      _ps      = nil end
    if _texture then _texture:release(); _texture = nil end
end\(burstHelpers)

return \(ident)
"""
    }

    // MARK: - Helpers

    // MARK: - Canvas shape code

    private static func canvasShapeCode(_ shape: ParticleShape, size: Int) -> String {
        let h = size / 2
        let s = size
        switch shape {

        case .circle:
            return "        love.graphics.circle(\"fill\", \(h), \(h), \(h))"

        case .square:
            return "        love.graphics.rectangle(\"fill\", 2, 2, \(s-4), \(s-4))"

        case .triangle:
            return "        love.graphics.polygon(\"fill\", \(h), 2, \(s-2), \(s-2), 2, \(s-2))"

        case .star:
            let r1 = h - 2
            let r2 = Int(Double(r1) * 0.42)
            // Decompose into 2*n triangles all anchored at the centre.
            // Every triangle is convex by definition, so polygon("fill") is safe.
            //   odd  triangles: centre → outer[i]   → inner[i]
            //   even triangles: centre → inner[i]   → outer[i+1]
            return
                "        local function _drawStar(cx, cy, r1, r2, n)\n" +
                "            local pi2n = math.pi * 2 / n\n" +
                "            local off  = -math.pi / 2\n" +
                "            for i = 0, n-1 do\n" +
                "                local ao  = pi2n * i       + off\n" +
                "                local ai  = pi2n * i + pi2n/2 + off\n" +
                "                local ao2 = pi2n * (i+1)   + off\n" +
                "                local ox  = cx + math.cos(ao)*r1\n" +
                "                local oy  = cy + math.sin(ao)*r1\n" +
                "                local ix  = cx + math.cos(ai)*r2\n" +
                "                local iy  = cy + math.sin(ai)*r2\n" +
                "                local ox2 = cx + math.cos(ao2)*r1\n" +
                "                local oy2 = cy + math.sin(ao2)*r1\n" +
                "                love.graphics.polygon(\"fill\", cx, cy, ox, oy, ix, iy)\n" +
                "                love.graphics.polygon(\"fill\", cx, cy, ix, iy, ox2, oy2)\n" +
                "            end\n" +
                "        end\n" +
                "        _drawStar(\(h), \(h), \(r1), \(r2), 5)"

        case .ring:
            let lw = max(s / 6, 4)
            let r  = h - lw
            return
                "        love.graphics.setLineWidth(\(lw))\n" +
                "        love.graphics.circle(\"line\", \(h), \(h), \(r))\n" +
                "        love.graphics.setLineWidth(1)"

        case .diamond:
            return "        love.graphics.polygon(\"fill\", \(h), 2, \(s-2), \(h), \(h), \(s-2), 2, \(h))"
        }
    }

    private static func fmt2(_ v: Double) -> String { String(format: "%.2f", v) }
    private static func fmt3(_ v: Double) -> String { String(format: "%.3f", v) }
    private static func fmt4(_ v: Double) -> String { String(format: "%.4f", v) }

    private static func directionLabel(_ deg: Double) -> String {
        let d = ((deg.truncatingRemainder(dividingBy: 360)) + 360)
            .truncatingRemainder(dividingBy: 360)
        switch d {
        case 0..<23:    return "right"
        case 23..<68:   return "up-right"
        case 68..<113:  return "up"
        case 113..<158: return "up-left"
        case 158..<203: return "left"
        case 203..<248: return "down-left"
        case 248..<293: return "down"
        case 293..<338: return "down-right"
        default:        return "right"
        }
    }

    private static func luaIdent(_ name: String) -> String {
        let safe = name
            .components(separatedBy: CharacterSet.alphanumerics.union(.init(charactersIn: "_")).inverted)
            .joined(separator: "_")
            .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        let result = safe.isEmpty ? "particles" : safe
        return result.first?.isNumber == true ? "_\(result)" : result
    }
}
