import Foundation

struct ResolutionCodeGenerator {

    static func generate(config: ResolutionConfig) -> String {
        let mod  = luaIdent(config.moduleName.isEmpty ? "Resolution" : config.moduleName)
        let vw   = config.virtualWidth
        let vh   = config.virtualHeight
        let filt = config.filterMode.rawValue

        // Scale + offset calculation per mode
        let resizeBody: String
        switch config.scalingMode {
        case .pixelPerfect:
            resizeBody = """
    local sx = math.floor(w / VIRTUAL_W)
    local sy = math.floor(h / VIRTUAL_H)
    _scale    = math.max(1, math.min(sx, sy))
    _ox       = math.floor((w - VIRTUAL_W * _scale) * 0.5)
    _oy       = math.floor((h - VIRTUAL_H * _scale) * 0.5)
"""
        case .letterbox:
            resizeBody = """
    local sx  = w / VIRTUAL_W
    local sy  = h / VIRTUAL_H
    _scale    = math.min(sx, sy)
    _ox       = math.floor((w - VIRTUAL_W * _scale) * 0.5)
    _oy       = math.floor((h - VIRTUAL_H * _scale) * 0.5)
"""
        case .stretch:
            resizeBody = """
    _scaleX = w / VIRTUAL_W
    _scaleY = h / VIRTUAL_H
    _scale  = 1   -- not used for draw, kept for toGame()
    _ox, _oy = 0, 0
"""
        }

        let drawCall: String
        if config.scalingMode == .stretch {
            drawCall = "    love.graphics.draw(_canvas, 0, 0, 0, _scaleX, _scaleY)"
        } else {
            drawCall = "    love.graphics.draw(_canvas, _ox, _oy, 0, _scale, _scale)"
        }

        let extraVars = config.scalingMode == .stretch
            ? "\nlocal _scaleX, _scaleY = 1, 1" : ""

        let toGameBody: String
        if config.scalingMode == .stretch {
            toGameBody = "    return sx / _scaleX, sy / _scaleY"
        } else {
            toGameBody = "    return (sx - _ox) / _scale, (sy - _oy) / _scale"
        }

        let modeComment: String
        switch config.scalingMode {
        case .pixelPerfect:
            modeComment = "-- Scaling: pixel-perfect integer scale - sharpest pixels, possible black bars"
        case .letterbox:
            modeComment = "-- Scaling: letterbox - maintains aspect ratio, possible black bars"
        case .stretch:
            modeComment = "-- Scaling: stretch - fills the entire window, may distort"
        }

        return """
--------------------------------------------------------------------------------
-- \(mod).lua
-- Generated by LÖVE Studio · Resolution Scaler
--------------------------------------------------------------------------------
--
-- QUICK START
-- -----------
-- 1. Require at the top of main.lua:
--
--      local \(mod) = require("\(mod.lowercased())")
--
-- 2. Initialize in love.load() and handle resize:
--
--      function love.load()
--          \(mod):load()
--      end
--
--      function love.resize(w, h)
--          \(mod):resize(w, h)
--      end
--
-- 3. Wrap ALL drawing in love.draw():
--
--      function love.draw()
--          \(mod):begin()
--              -- draw your entire game here
--              -- coordinates are in virtual pixels (0–\(vw), 0–\(vh))
--              love.graphics.draw(player.img, player.x, player.y)
--              love.graphics.print("Score: " .. score, 4, 4)
--          \(mod):finish()
--
--          -- anything drawn here is in real screen coordinates
--          -- and is NOT scaled (useful for overlays, debug UI, etc.)
--      end
--
-- 4. Convert mouse / touch input to virtual coordinates:
--
--      function love.mousepressed(x, y, btn)
--          local gx, gy = \(mod):toGame(x, y)
--          -- gx, gy are now in virtual pixel space
--      end
--
-- VIRTUAL RESOLUTION  \(vw) × \(vh) px
\(modeComment)
-- Filter: \(filt)  (\(filt == "nearest" ? "pixel-art sharp" : "smooth bilinear"))
--------------------------------------------------------------------------------

local \(mod) = {}

local VIRTUAL_W = \(vw)
local VIRTUAL_H = \(vh)
local FILTER    = "\(filt)"

local _canvas = nil
local _scale  = 1
local _ox, _oy = 0, 0\(extraVars)

--------------------------------------------------------------------------------
-- \(mod):load()
-- Creates the canvas and computes the initial scale.
-- Call once in love.load().
--------------------------------------------------------------------------------
function \(mod):load()
    love.graphics.setDefaultFilter(FILTER, FILTER)
    _canvas = love.graphics.newCanvas(VIRTUAL_W, VIRTUAL_H)
    _canvas:setFilter(FILTER, FILTER)
    self:resize(love.graphics.getDimensions())
end

--------------------------------------------------------------------------------
-- \(mod):resize(w, h)
-- Recomputes scale and letterbox offsets when the window is resized.
-- Call from love.resize(w, h).
--------------------------------------------------------------------------------
function \(mod):resize(w, h)
\(resizeBody)end

--------------------------------------------------------------------------------
-- \(mod):begin()
-- Redirects all drawing to the virtual canvas.
-- Call at the start of love.draw().
--------------------------------------------------------------------------------
function \(mod):begin()
    love.graphics.setCanvas(_canvas)
    love.graphics.clear()
end

--------------------------------------------------------------------------------
-- \(mod):finish()
-- Stops drawing to the canvas and scales it onto the screen.
-- Call at the end of love.draw() (before any HUD drawn in screen coords).
--------------------------------------------------------------------------------
function \(mod):finish()
    love.graphics.setCanvas()
    love.graphics.clear(0, 0, 0)
\(drawCall)
end

--------------------------------------------------------------------------------
-- \(mod):toGame(sx, sy) → gx, gy
-- Converts real screen coordinates (e.g. mouse position) to virtual game coords.
--------------------------------------------------------------------------------
function \(mod):toGame(sx, sy)
\(toGameBody)
end

--------------------------------------------------------------------------------
-- \(mod):getVirtualSize() → w, h
-- Returns the virtual canvas dimensions.
--------------------------------------------------------------------------------
function \(mod):getVirtualSize()
    return VIRTUAL_W, VIRTUAL_H
end

--------------------------------------------------------------------------------
-- \(mod):getScale() → scale
-- Returns the current scale factor (useful for drawing UI at a fixed size).
--------------------------------------------------------------------------------
function \(mod):getScale()
    return _scale
end

return \(mod)
"""
    }

    // MARK: - Helpers

    private static func luaIdent(_ name: String) -> String {
        let safe = name
            .components(separatedBy: CharacterSet.alphanumerics.union(.init(charactersIn: "_")).inverted)
            .joined(separator: "_")
            .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        let result = safe.isEmpty ? "Resolution" : safe
        return result.first?.isNumber == true ? "_\(result)" : result
    }
}
