import Foundation

struct SaveCodeGenerator {

    static func generate(config: SaveSystemConfig) -> String {
        let mod      = luaIdent(config.moduleName.isEmpty ? "Save" : config.moduleName)
        let fileName = config.fileName.isEmpty ? "savegame" : config.fileName
        let fields   = config.fields

        // Defaults table
        let defaultLines = fields.map { f -> String in
            let key  = luaIdent(f.name)
            let val  = f.defaultValue.trimmingCharacters(in: .whitespaces)
            let safe = val.isEmpty ? f.type.defaultPlaceholder : val
            let desc = f.description.isEmpty ? "" : "  -- \(f.description)"
            return "    \(key.padding(toLength: 20, withPad: " ", startingAt: 0)) = \(safe),\(desc)"
        }.joined(separator: "\n")

        // Field list comment
        let fieldList = fields.map { f -> String in
            let key  = luaIdent(f.name)
            let desc = f.description.isEmpty ? "" : "  \(f.description)"
            return "--   \(key.padding(toLength: 20, withPad: " ", startingAt: 0))  [\(f.type.rawValue)]\(desc)"
        }.joined(separator: "\n")

        // Individual getter/setter helpers
        let getters = fields.map { f -> String in
            let key = luaIdent(f.name)
            return """
            --- Get \(key)
            function \(mod):get\(key.prefix(1).uppercased() + key.dropFirst())()
                return self.data.\(key)
            end

            --- Set \(key)
            function \(mod):set\(key.prefix(1).uppercased() + key.dropFirst())(value)
                self.data.\(key) = value
            end
            """
        }.joined(separator: "\n\n")

        return """
--------------------------------------------------------------------------------
-- \(mod).lua
-- Generated by LÖVE Studio · Save System
--------------------------------------------------------------------------------
--
-- QUICK START
-- -----------
-- 1. Require in main.lua:
--
--      local \(mod) = require("\(mod.lowercased())")
--
-- 2. Load save data in love.load():
--
--      function love.load()
--          \(mod):load()
--      end
--
-- 3. Read and write values:
--
--      \(mod).data.score = \(mod).data.score + 100
--      \(mod).data.level = \(mod).data.level + 1
--      print(\(mod).data.playerName)
--
-- 4. Save to disk (call whenever you want to persist):
--
--      \(mod):save()
--
-- 5. Reset to defaults (e.g. new game):
--
--      \(mod):reset()
--
-- 6. Delete save file:
--
--      \(mod):delete()
--
-- FIELDS  (\(fields.count) configured)
-- -------------------------------------------------------
\(fieldList.isEmpty ? "--   (none)" : fieldList)
-- -------------------------------------------------------
-- Save file: \(fileName).json  (in love.filesystem)
--------------------------------------------------------------------------------

local \(mod) = {}

--------------------------------------------------------------------------------
-- Default values - restored on reset() or when a key is missing from disk
--------------------------------------------------------------------------------
local _defaults = {
\(defaultLines.isEmpty ? "    -- (no fields configured)" : defaultLines)
}

-- Live data table - read/write your fields here
\(mod).data = {}

--------------------------------------------------------------------------------
-- Minimal JSON encoder / decoder (no external dependencies)
--------------------------------------------------------------------------------
local json = {}

local function _encodeValue(v, indent)
    local t = type(v)
    if t == "nil"     then return "null"
    elseif t == "boolean" then return tostring(v)
    elseif t == "number"  then
        if v ~= v then return "null" end  -- NaN
        return tostring(v)
    elseif t == "string"  then
        return '"' .. v:gsub('\\\\', '\\\\\\\\'):gsub('"', '\\\\"'):gsub('\\n', '\\\\n'):gsub('\\r', '\\\\r'):gsub('\\t', '\\\\t') .. '"'
    elseif t == "table"   then
        -- Array check
        local n = 0
        for _ in pairs(v) do n = n + 1 end
        local isArray = (#v == n)
        local parts = {}
        if isArray then
            for _, val in ipairs(v) do
                table.insert(parts, _encodeValue(val))
            end
            return "[" .. table.concat(parts, ",") .. "]"
        else
            for k, val in pairs(v) do
                table.insert(parts, '"' .. tostring(k) .. '":' .. _encodeValue(val))
            end
            return "{" .. table.concat(parts, ",") .. "}"
        end
    end
    return "null"
end

function json.encode(t) return _encodeValue(t) end

local function _skipWS(s, i)
    while i <= #s and s:sub(i,i):match("%s") do i = i + 1 end
    return i
end

local function _parseValue(s, i)
    i = _skipWS(s, i)
    local c = s:sub(i,i)
    if c == '"' then
        local j = i + 1
        local result = ""
        while j <= #s do
            local ch = s:sub(j,j)
            if ch == '\\\\' then
                local esc = s:sub(j+1,j+1)
                if     esc == '"'  then result = result .. '"'
                elseif esc == '\\\\' then result = result .. '\\\\'
                elseif esc == 'n'  then result = result .. '\\n'
                elseif esc == 'r'  then result = result .. '\\r'
                elseif esc == 't'  then result = result .. '\\t'
                else result = result .. esc end
                j = j + 2
            elseif ch == '"' then
                return result, j + 1
            else
                result = result .. ch; j = j + 1
            end
        end
        return result, j
    elseif c == '{' then
        local obj = {}; i = i + 1
        i = _skipWS(s, i)
        if s:sub(i,i) == '}' then return obj, i + 1 end
        while true do
            i = _skipWS(s, i)
            local k; k, i = _parseValue(s, i)
            i = _skipWS(s, i); i = i + 1  -- skip ':'
            local v; v, i = _parseValue(s, i)
            obj[k] = v
            i = _skipWS(s, i)
            local sep = s:sub(i,i); i = i + 1
            if sep == '}' then break end
        end
        return obj, i
    elseif c == '[' then
        local arr = {}; i = i + 1
        i = _skipWS(s, i)
        if s:sub(i,i) == ']' then return arr, i + 1 end
        while true do
            local v; v, i = _parseValue(s, i)
            table.insert(arr, v)
            i = _skipWS(s, i)
            local sep = s:sub(i,i); i = i + 1
            if sep == ']' then break end
        end
        return arr, i
    elseif s:sub(i, i+3) == "true"  then return true,  i + 4
    elseif s:sub(i, i+4) == "false" then return false, i + 5
    elseif s:sub(i, i+3) == "null"  then return nil,   i + 4
    else
        local num = s:match("^-?%d+%.?%d*[eE]?[+-]?%d*", i)
        if num then return tonumber(num), i + #num end
    end
    return nil, i + 1
end

function json.decode(s)
    local ok, result = pcall(function()
        local v = _parseValue(s, 1)
        return v
    end)
    return ok and result or nil
end

--------------------------------------------------------------------------------
-- \(mod):load()
-- Reads the save file from disk and merges with defaults.
-- Safe to call even if no save file exists yet.
--------------------------------------------------------------------------------
function \(mod):load()
    -- Start from defaults
    self:reset()
    local raw = love.filesystem.read("\(fileName).json")
    if not raw then return end  -- first launch, no save yet
    local decoded = json.decode(raw)
    if type(decoded) ~= "table" then
        print("[\(mod)] WARNING: save file is corrupt, using defaults.")
        return
    end
    -- Merge saved values over defaults (preserves new fields added after saving)
    for k, v in pairs(decoded) do
        self.data[k] = v
    end
end

--------------------------------------------------------------------------------
-- \(mod):save()
-- Serialises data to JSON and writes to love.filesystem.
-- Call this whenever you want to persist the current state.
--------------------------------------------------------------------------------
function \(mod):save()
    local encoded = json.encode(self.data)
    local ok, err = love.filesystem.write("\(fileName).json", encoded)
    if not ok then
        print("[\(mod)] ERROR: could not write save file - " .. tostring(err))
    end
end

--------------------------------------------------------------------------------
-- \(mod):reset()
-- Resets all fields to their default values (does NOT delete the file on disk).
-- Call save() afterwards if you want to persist the reset.
--------------------------------------------------------------------------------
function \(mod):reset()
    self.data = {}
    for k, v in pairs(_defaults) do
        -- Deep-copy tables so each reset gets a fresh table, not a shared ref
        if type(v) == "table" then
            local copy = {}
            for tk, tv in pairs(v) do copy[tk] = tv end
            self.data[k] = copy
        else
            self.data[k] = v
        end
    end
end

--------------------------------------------------------------------------------
-- \(mod):delete()
-- Removes the save file from disk and resets data to defaults.
--------------------------------------------------------------------------------
function \(mod):delete()
    love.filesystem.remove("\(fileName).json")
    self:reset()
end

--------------------------------------------------------------------------------
-- \(mod):exists() → boolean
-- Returns true if a save file exists on disk.
--------------------------------------------------------------------------------
function \(mod):exists()
    return love.filesystem.getInfo("\(fileName).json") ~= nil
end

\(getters.isEmpty ? "" : """
--------------------------------------------------------------------------------
-- Typed getters / setters for each field
-- (Convenience wrappers around Save.data - feel free to use .data directly too)
--------------------------------------------------------------------------------

\(getters)
""")
return \(mod)
"""
    }

    // MARK: - JSON preview (what the save file looks like)

    static func jsonPreview(config: SaveSystemConfig) -> String {
        let fields = config.fields
        guard !fields.isEmpty else { return "{\n}" }
        let lines = fields.map { f -> String in
            let key  = luaIdent(f.name)
            let val  = f.defaultValue.trimmingCharacters(in: .whitespaces)
            let safe = val.isEmpty ? f.type.defaultPlaceholder : val
            // Convert Lua literal → JSON-ish representation
            let jsonVal: String
            switch f.type {
            case .boolean: jsonVal = (safe == "true") ? "true" : "false"
            case .number:  jsonVal = safe.isEmpty ? "0" : safe
            case .string:
                let stripped = safe.hasPrefix("\"") && safe.hasSuffix("\"")
                    ? String(safe.dropFirst().dropLast()) : safe
                jsonVal = "\"\(stripped)\""
            case .table:   jsonVal = safe == "{}" ? "[]" : safe
            }
            return "    \"\(key)\": \(jsonVal)"
        }
        return "{\n" + lines.joined(separator: ",\n") + "\n}"
    }

    static func luaIdent(_ name: String) -> String {
        let safe = name
            .components(separatedBy: CharacterSet.alphanumerics.union(.init(charactersIn: "_")).inverted)
            .joined(separator: "_")
            .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        let result = safe.isEmpty ? "field" : safe
        return result.first?.isNumber == true ? "_\(result)" : result
    }
}
