import Foundation

struct SpritesheetCodeGenerator {

    static func generate(config: SpritesheetConfig, packResult: PackResult) -> String {
        let mod     = luaIdent(config.projectName.isEmpty ? "Sprites" : config.projectName)
        let atlas   = config.atlasPath.isEmpty ? "sprites/atlas.png" : config.atlasPath
        let atW     = Int(packResult.atlasSize.width)
        let atH     = Int(packResult.atlasSize.height)

        // Quad lines — one per packed sprite
        let quadLines = packResult.packed.map { p -> String in
            let key = luaIdent(p.entry.name)
            let x   = Int(p.rect.origin.x)
            let y   = Int(p.rect.origin.y)
            let w   = Int(p.rect.size.width)
            let h   = Int(p.rect.size.height)
            return "    _quads.\(key) = love.graphics.newQuad(\(x), \(y), \(w), \(h), _aw, _ah)"
        }.joined(separator: "\n")

        // Failed entries comment (if any)
        let failedComment: String
        if !packResult.failed.isEmpty {
            let names = packResult.failed.map { "-- · \($0.name)  (\($0.filePath))" }.joined(separator: "\n")
            failedComment = """
--
-- WARNING: The following sprites could not be packed (file not found):
\(names)
--
"""
        } else {
            failedComment = ""
        }

        // Sprite list comment
        let spriteListLines = packResult.packed.map { p -> String in
            let key    = luaIdent(p.entry.name)
            let padded = key.padding(toLength: 24, withPad: " ", startingAt: 0)
            let x = Int(p.rect.origin.x), y = Int(p.rect.origin.y)
            let w = Int(p.rect.size.width), h = Int(p.rect.size.height)
            return "--   \(padded)  x=\(x)  y=\(y)  w=\(w)  h=\(h)"
        }.joined(separator: "\n")

        return """
--------------------------------------------------------------------------------
-- \(mod).lua
-- Generated by LÖVE Studio · Spritesheet Packer
--------------------------------------------------------------------------------
--
-- QUICK START
-- -----------
-- 1. Require this module in main.lua:
--
--      local \(mod) = require("\(mod.lowercased())")
--
-- 2. Load the atlas in love.load():
--
--      function love.load()
--          \(mod):load()
--      end
--
-- 3. Draw a sprite anywhere:
--
--      \(mod):draw("player", x, y)
--      \(mod):draw("player", x, y, angle, scaleX, scaleY)
--
-- 4. Access the raw quad / atlas:
--
--      local q = \(mod):getQuad("enemy")
--      local t = \(mod):getAtlas()
--      love.graphics.draw(t, q, x, y)
--
\(failedComment)-- SPRITES  (\(packResult.packed.count) packed  |  atlas \(atW)×\(atH)px)
-- -------------------------------------------------------
\(spriteListLines)
-- -------------------------------------------------------
-- Atlas: \(atlas)
--------------------------------------------------------------------------------

local \(mod) = {}

local _atlas = nil
local _aw, _ah = 0, 0
local _quads = {}

--------------------------------------------------------------------------------
-- \(mod):load()
--------------------------------------------------------------------------------
function \(mod):load()
    _atlas = love.graphics.newImage("\(atlas)")
    _aw, _ah = _atlas:getDimensions()
\(quadLines)
end

--------------------------------------------------------------------------------
-- \(mod):draw(name, x, y [, r, sx, sy, ox, oy])
--------------------------------------------------------------------------------
function \(mod):draw(name, x, y, r, sx, sy, ox, oy)
    local q = _quads[name]
    if q and _atlas then
        love.graphics.draw(_atlas, q, x, y, r or 0, sx or 1, sy or 1, ox or 0, oy or 0)
    end
end

--------------------------------------------------------------------------------
-- \(mod):drawCentered(name, x, y [, r, sx, sy])
-- Draws the sprite with origin at its center.
--------------------------------------------------------------------------------
function \(mod):drawCentered(name, x, y, r, sx, sy)
    local q = _quads[name]
    if q and _atlas then
        local _, _, qw, qh = q:getViewport()
        love.graphics.draw(_atlas, q, x, y, r or 0, sx or 1, sy or 1, qw * 0.5, qh * 0.5)
    end
end

--------------------------------------------------------------------------------
-- \(mod):getQuad(name) -> Quad | nil
--------------------------------------------------------------------------------
function \(mod):getQuad(name)
    return _quads[name]
end

--------------------------------------------------------------------------------
-- \(mod):getAtlas() -> Image | nil
--------------------------------------------------------------------------------
function \(mod):getAtlas()
    return _atlas
end

--------------------------------------------------------------------------------
-- \(mod):getSize(name) -> w, h
--------------------------------------------------------------------------------
function \(mod):getSize(name)
    local q = _quads[name]
    if not q then return 0, 0 end
    local _, _, w, h = q:getViewport()
    return w, h
end

--------------------------------------------------------------------------------
-- \(mod):unload()
--------------------------------------------------------------------------------
function \(mod):unload()
    _atlas = nil
    _quads = {}
end

return \(mod)
"""
    }

    // MARK: - JSON metadata

    static func generateJSON(config: SpritesheetConfig, packResult: PackResult) -> String {
        let mod   = luaIdent(config.projectName.isEmpty ? "Sprites" : config.projectName)
        let atlas = config.atlasPath.isEmpty ? "sprites/atlas.png" : config.atlasPath
        let atW   = Int(packResult.atlasSize.width)
        let atH   = Int(packResult.atlasSize.height)

        var lines: [String] = []
        lines.append("{")
        lines.append("  \"meta\": {")
        lines.append("    \"module\": \"\(mod)\",")
        lines.append("    \"atlas\": \"\(atlas)\",")
        lines.append("    \"size\": { \"w\": \(atW), \"h\": \(atH) },")
        lines.append("    \"generator\": \"LOVE Studio · Spritesheet Packer\"")
        lines.append("  },")
        lines.append("  \"sprites\": [")

        let sprites = packResult.packed
        for (i, p) in sprites.enumerated() {
            let key   = luaIdent(p.entry.name)
            let x     = Int(p.rect.origin.x)
            let y     = Int(p.rect.origin.y)
            let w     = Int(p.rect.size.width)
            let h     = Int(p.rect.size.height)
            let comma = i < sprites.count - 1 ? "," : ""
            lines.append("    { \"name\": \"\(key)\", \"x\": \(x), \"y\": \(y), \"w\": \(w), \"h\": \(h) }\(comma)")
        }

        lines.append("  ]")
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Helpers

    static func luaIdent(_ name: String) -> String {
        let safe = name
            .components(separatedBy: CharacterSet.alphanumerics.union(.init(charactersIn: "_")).inverted)
            .joined(separator: "_")
            .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        let result = safe.isEmpty ? "sprite" : safe
        return result.first?.isNumber == true ? "_\(result)" : result
    }
}
