import Foundation

struct UICodeGenerator {

    static func generate(config: UIBuilderConfig) -> String {
        let mod  = luaIdent(config.moduleName.isEmpty ? "UI" : config.moduleName)
        let elementCount = config.elements.count

        // Per-element state init + draw/update code
        let elementInits   = config.elements.map { elementInitLua($0, mod: mod) }.joined(separator: "\n\n")
        let drawCalls      = config.elements.map { "    \(mod)._draw_\(luaIdent($0.name))()" }
        let updateCalls    = config.elements.map { "    \(mod)._update_\(luaIdent($0.name))(dt)" }
        let mpCalls        = config.elements.map { "    \(mod)._mp_\(luaIdent($0.name))(x,y,btn)" }
        let mrCalls        = config.elements.map { "    \(mod)._mr_\(luaIdent($0.name))(x,y,btn)" }
        let mmCalls        = config.elements.map { "    \(mod)._mm_\(luaIdent($0.name))(x,y,dx,dy,istouch)" }
        let elementFuncs   = config.elements.map { elementFunctionsLua($0, mod: mod) }.joined(separator: "\n\n")
        let drawBody       = blockOrComment(drawCalls, empty: "Nothing to draw yet. Add elements in UI Builder.")
        let updateBody     = blockOrComment(updateCalls, empty: "No animated or dragging widgets configured yet.")
        let mousePressBody = blockOrComment(mpCalls, empty: "No clickable widgets yet.")
        let mouseReleaseBody = blockOrComment(mrCalls, empty: "No mouse release handlers yet.")
        let mouseMoveBody  = blockOrComment(mmCalls, empty: "No hover handlers yet.")
        let textInputBody  = textInputHandlerBody(config: config, mod: mod)
        let keyPressedBody = keyPressedHandlerBody(config: config, mod: mod)
        let keyReleasedBody = "    -- Reserved for future keyboard-release behavior.\n    -- Safe to keep this forwarded from main.lua even when unused."
        let wheelMovedBody = wheelMovedHandlerBody(config: config, mod: mod)

        // Collect unique Font Manager modules used by elements
        let usedFontMods: [String] = Array(Set(
            config.elements.compactMap { e -> String? in
                let m = e.style.fontManagerModule
                return m.isEmpty ? nil : m
            }
        )).sorted()

        // Element list comment
        let elementList = config.elements.map { e in
            let key = luaIdent(e.name)
            return "--   \(key.padding(toLength: 24, withPad: " ", startingAt: 0))  \(e.type.displayName)  (\(Int(e.x)), \(Int(e.y)))  \(Int(e.width))×\(Int(e.height))"
        }.joined(separator: "\n")

        return """
--------------------------------------------------------------------------------
-- \(mod).lua
-- Generated by LÖVE Studio · UI Builder
--------------------------------------------------------------------------------
--
-- QUICK START
-- -----------
-- 1. Require in main.lua:
--
--      local \(mod) = require("\(mod)")
--
-- 2. Hook ALL common love callbacks:
--
--      function love.load()
--          \(mod):load()
--      end
--
--      function love.update(dt)
--          \(mod):update(dt)
--      end
--
--      function love.draw()
--          \(mod):draw()
--      end
--
--      function love.mousepressed(x, y, btn)
--          \(mod):mousepressed(x, y, btn)
--      end
--
--      function love.mousereleased(x, y, btn)
--          \(mod):mousereleased(x, y, btn)
--      end
--
--      function love.mousemoved(x, y, dx, dy, istouch)
--          \(mod):mousemoved(x, y, dx, dy, istouch)
--      end
--
--      function love.textinput(t)
--          \(mod):textinput(t)
--      end
--
--      function love.keypressed(key, scancode, isrepeat)
--          \(mod):keypressed(key, scancode, isrepeat)
--      end
--
--      function love.keyreleased(key, scancode)
--          \(mod):keyreleased(key, scancode)
--      end
--
--      function love.wheelmoved(dx, dy)
--          \(mod):wheelmoved(dx, dy)
--      end
--
-- 3. Listen for element events:
--
--      \(mod).on.\(config.elements.first.map { luaIdent($0.name) } ?? "myButton") = function(e)
--          print("clicked!", e.label)
--      end
--
--      \(mod).on.\(config.elements.first(where: { $0.type == .slider }).map { luaIdent($0.name) } ?? "mySlider") = function(e)
--          print("value:", e.value)
--      end
--
-- HOW THIS MODULE WORKS
-- ---------------------
-- • Every UI element is stored in a local table named like `_playButton`.
-- • `:draw()` only renders current state.
-- • `:update(dt)` handles dragging / runtime state changes.
-- • Mouse callbacks keep hover / press / drag state in sync.
-- • Keyboard callbacks are always generated so text inputs can work immediately.
-- • You can freely read / mutate element state at runtime through `\(mod).el`:
--
--      -- Move a widget:
--      -- \(mod).el.playButton.x = 200
--      --
--      -- Change a label:
--      -- \(mod).el.scoreLabel.label = "Score: " .. tostring(score)
--      --
--      -- Update a progress bar:
--      -- \(mod).el.hpBar.value = player.hp / player.maxHp
--
-- EXAMPLES FOR EVERY WIDGET TYPE
-- ------------------------------
-- Button:
--      \(mod).on.myButton = function(e)
--          print("Button clicked:", e.label)
--      end
--
-- Label:
--      -- Labels are display-only.
--      -- Change text at runtime:
--      -- \(mod).el.myLabel.label = "Wave " .. wave
--
-- Slider:
--      \(mod).on.mySlider = function(e)
--          print("Slider value:", e.value)
--      end
--
-- Checkbox:
--      \(mod).on.myCheckbox = function(e)
--          print("Checkbox checked:", e.checked)
--      end
--
-- Radio Button:
--      \(mod).on.myRadio = function(e)
--          print("Radio selected:", e.checked)
--      end
--
-- Progress Bar:
--      -- Usually driven by gameplay code:
--      -- \(mod).el.myProgress.value = currentHP / maxHP
--
-- Panel:
--      -- Decorative / grouping element.
--      -- You can change title text:
--      -- \(mod).el.myPanel.label = "Inventory"
--
-- Text Input:
--      \(mod).on.myInput = function(e)
--          print("Typed text:", e.text)
--      end
--      -- Keyboard support is generated automatically:
--      -- textinput -> appends characters
--      -- keypressed(backspace) -> deletes last character
--      -- keypressed(escape) -> unfocuses
--
-- Image:
--      -- Image widgets stretch the texture to widget bounds.
--      -- Swap image at runtime:
--      -- \(mod).el.myImage.image = love.graphics.newImage("images/other.png")
--
-- Scroll Bar:
--      \(mod).on.myScroll = function(e)
--          print("Scroll value:", e.value)
--      end
--      -- Mouse wheel over the scrollbar also updates the value.
--
-- ELEMENTS  (\(elementCount) configured)
-- -------------------------------------------------------
\(elementList.isEmpty ? "--   (none)" : elementList)
-- -------------------------------------------------------
-- Canvas: \(config.canvasWidth) × \(config.canvasHeight) px
--------------------------------------------------------------------------------

local \(mod) = {}
local utf8 = require("utf8")

-- Event callbacks — assign a function to be notified when an element fires.
-- e.g.  \(mod).on.myButton = function(el) ... end
\(mod).on = {}

-- Public handles to generated element state tables.
-- Example: \(mod).el.playButton.label = "Resume"
\(mod).el = {}

-- Internal font cache (fallback when no Font Manager key is set)
local _font = nil
local function _getFont(size)
    if not _font or _font:getHeight() ~= size then
        _font = love.graphics.newFont(size)
    end
    return _font
end

-- Font Manager module cache (required + loaded on first use)
local _fmCache = {}
local function _getFontMod(name)
    if not name or name == "" then return nil end
    if _fmCache[name] == nil then
        local ok, m = pcall(require, name:lower())
        if ok and m then
            -- Auto-load fonts if the module exposes :load()
            if m.load then pcall(m.load, m) end
            _fmCache[name] = m
        else
            _fmCache[name] = false
        end
    end
    return _fmCache[name] or nil
end

-- Set font for an element: uses Font Manager module if configured, else _getFont
-- Returns true if Font Manager was used (caller must call _restoreElemFont).
local function _setElemFont(e)
    if e.style.fontMod and e.style.fontMod ~= "" and e.style.fontKey and e.style.fontKey ~= "" then
        local mod = _getFontMod(e.style.fontMod)
        if mod then mod:set(e.style.fontKey); return true end
    end
    love.graphics.setFont(_getFont(e.style.fontSize))
    return false
end

local function _restoreElemFont(e, usedMod)
    if usedMod then
        local mod = _getFontMod(e.style.fontMod)
        if mod then mod:restore() end
    end
end

-- Draw text through Font Manager (includes outline) or plain love.graphics
-- printf variant: wraps text to 'limit' width with alignment
local function _fmPrintf(e, text, x, y, limit, align)
    if e.style.fontMod and e.style.fontMod ~= "" and e.style.fontKey and e.style.fontKey ~= "" then
        local mod = _getFontMod(e.style.fontMod)
        if mod then mod:printf(e.style.fontKey, text, x, y, limit, align); return end
    end
    love.graphics.setFont(_getFont(e.style.fontSize))
    love.graphics.printf(text, x, y, limit, align)
end

-- print variant: single-line text
local function _fmPrint(e, text, x, y)
    if e.style.fontMod and e.style.fontMod ~= "" and e.style.fontKey and e.style.fontKey ~= "" then
        local mod = _getFontMod(e.style.fontMod)
        if mod then mod:print(e.style.fontKey, text, x, y); return end
    end
    love.graphics.setFont(_getFont(e.style.fontSize))
    love.graphics.print(text, x, y)
end

-- Helper: is point inside rect?
local function _inRect(px, py, x, y, w, h)
    return px >= x and px <= x+w and py >= y and py <= y+h
end

-- Helper: draw rounded rectangle with border
local function _drawBox(x, y, w, h, r, bg, border, bw)
    love.graphics.setColor(bg)
    love.graphics.rectangle("fill", x, y, w, h, r)
    if bw > 0 then
        love.graphics.setColor(border)
        love.graphics.setLineWidth(bw)
        love.graphics.rectangle("line", x, y, w, h, r)
    end
end

--------------------------------------------------------------------------------
-- Element state tables + per-element functions
--------------------------------------------------------------------------------

\(elementInits)

\(elementFuncs)

--------------------------------------------------------------------------------
-- \(mod):load()
--------------------------------------------------------------------------------
function \(mod):load()
\(usedFontMods.isEmpty
    ? "    -- No Font Manager modules linked."
    : "    -- Pre-load linked Font Manager modules\n" + usedFontMods.map { "    _getFontMod(\"\($0)\")" }.joined(separator: "\n"))
end

--------------------------------------------------------------------------------
-- \(mod):update(dt)
--------------------------------------------------------------------------------
function \(mod):update(dt)
\(updateBody)
end

--------------------------------------------------------------------------------
-- \(mod):draw()
--------------------------------------------------------------------------------
function \(mod):draw()
\(drawBody)
end

--------------------------------------------------------------------------------
-- \(mod):mousepressed(x, y, btn)
--------------------------------------------------------------------------------
function \(mod):mousepressed(x, y, btn)
\(mousePressBody)
end

--------------------------------------------------------------------------------
-- \(mod):mousereleased(x, y, btn)
--------------------------------------------------------------------------------
function \(mod):mousereleased(x, y, btn)
\(mouseReleaseBody)
end

--------------------------------------------------------------------------------
-- \(mod):mousemoved(x, y, dx, dy, istouch)
--------------------------------------------------------------------------------
function \(mod):mousemoved(x, y, dx, dy, istouch)
\(mouseMoveBody)
end

--------------------------------------------------------------------------------
-- \(mod):textinput(t)
-- Forward love.textinput events to focused text inputs.
--------------------------------------------------------------------------------
function \(mod):textinput(t)
\(textInputBody)
end

--------------------------------------------------------------------------------
-- \(mod):keypressed(key, scancode, isrepeat)
-- Handles generated keyboard behavior, especially for text inputs.
--------------------------------------------------------------------------------
function \(mod):keypressed(key, scancode, isrepeat)
\(keyPressedBody)
end

--------------------------------------------------------------------------------
-- \(mod):keyreleased(key, scancode)
--------------------------------------------------------------------------------
function \(mod):keyreleased(key, scancode)
\(keyReleasedBody)
end

--------------------------------------------------------------------------------
-- \(mod):wheelmoved(dx, dy)
--------------------------------------------------------------------------------
function \(mod):wheelmoved(dx, dy)
\(wheelMovedBody)
end

return \(mod)
"""
    }

    // MARK: - Element state init

    private static func elementInitLua(_ e: UIElement, mod: String) -> String {
        let key = luaIdent(e.name)
        let s   = e.style
        var lines: [String] = [
            "-- \(e.type.displayName): \(e.name)",
            "local _\(key) = {",
            "    name     = \"\(key)\",",
            "    type     = \"\(e.type.rawValue)\",",
            "    label    = \"\(e.label.replacingOccurrences(of: "\"", with: "\\\""))\",",
            "    x        = \(fmt(e.x)),",
            "    y        = \(fmt(e.y)),",
            "    w        = \(fmt(e.width)),",
            "    h        = \(fmt(e.height)),",
            "    enabled  = \(e.enabled ? "true" : "false"),",
            "    hovered  = false,",
            "    pressed  = false,",
            "    style = {",
            "        bg       = \(s.bgColor.lua),",
            "        hover    = \(s.hoverColor.lua),",
            "        press    = \(s.pressColor.lua),",
            "        text     = \(s.textColor.lua),",
            "        border   = \(s.borderColor.lua),",
            "        accent   = \(s.accentColor.lua),",
            "        track    = \(s.trackColor.lua),",
            "        thumb    = \(s.thumbColor.lua),",
            "        radius   = \(fmt(s.cornerRadius)),",
            "        bw       = \(fmt(s.borderWidth)),",
            "        fontSize = \(fmt(s.fontSize)),",
            "        padding  = \(fmt(s.padding)),",
            "        thumbSz  = \(fmt(s.thumbSize)),",
            s.fontManagerModule.isEmpty ? "" :
            "        fontMod  = \"\(s.fontManagerModule)\",",
            s.fontManagerKey.isEmpty ? "" :
            "        fontKey  = \"\(s.fontManagerKey)\",",
            "    },",
        ]

        switch e.type {
        case .slider, .progressBar:
            lines += [
                "    value    = \(fmt(e.value)),",
                "    minValue = \(fmt(e.minValue)),",
                "    maxValue = \(fmt(e.maxValue)),",
                "    dragging = false,",
                "    horizontal = \(e.horizontal ? "true" : "false"),",
            ]
        case .checkbox, .radioButton:
            lines.append("    checked  = \(e.checked ? "true" : "false"),")
        case .textInput:
            lines += [
                "    text        = \"\",",
                "    placeholder = \"\(e.placeholder.replacingOccurrences(of: "\"", with: "\\\""))\",",
                "    focused     = false,",
                "    cursor      = 0,",
            ]
        case .scrollBar:
            lines += [
                "    value      = \(fmt(e.value)),",
                "    horizontal = \(e.horizontal ? "true" : "false"),",
                "    dragging   = false,",
            ]
        case .image:
            lines += [
                "    image = \(e.imagePath.isEmpty ? "nil" : "love.graphics.newImage(\(luaQuoted(e.imagePath)))"),",
            ]
        default: break
        }

        lines.append("}")
        lines.append("\(mod).el.\(key) = _\(key)")
        return lines.joined(separator: "\n")
    }

    // MARK: - Per-element functions

    private static func elementFunctionsLua(_ e: UIElement, mod: String) -> String {
        let key = luaIdent(e.name)
        switch e.type {
        case .button:      return buttonFuncs(key, mod: mod)
        case .label:       return labelFuncs(key, mod: mod, e: e)
        case .slider:      return sliderFuncs(key, mod: mod)
        case .progressBar: return progressFuncs(key, mod: mod)
        case .checkbox:    return checkboxFuncs(key, mod: mod)
        case .radioButton: return radioFuncs(key, mod: mod)
        case .panel:       return panelFuncs(key, mod: mod, e: e)
        case .textInput:   return textInputFuncs(key, mod: mod)
        case .image:       return imageFuncs(key, mod: mod)
        case .scrollBar:   return scrollBarFuncs(key, mod: mod)
        }
    }

    private static func buttonFuncs(_ key: String, mod: String) -> String { """
-- Button: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    local bg = e.pressed and e.style.press or (e.hovered and e.style.hover or e.style.bg)
    local pad = math.min(e.style.padding, math.max(2, e.w - 4))
    _drawBox(e.x, e.y, e.w, e.h, e.style.radius, bg, e.style.border, e.style.bw)
    love.graphics.setColor(e.style.text)
    _fmPrint(e, e.label, e.x + pad, e.y + (e.h - e.style.fontSize) * 0.5)
end
function \(mod)._update_\(key)(dt) end
function \(mod)._mp_\(key)(x,y,btn)
    if btn==1 and _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h) and _\(key).enabled then
        _\(key).pressed=true
    end
end
function \(mod)._mr_\(key)(x,y,btn)
    if btn==1 and _\(key).pressed then
        _\(key).pressed=false
        if _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h) then
            if \(mod).on.\(key) then \(mod).on.\(key)(_\(key)) end
        end
    end
end
    function \(mod)._mm_\(key)(x,y,dx,dy,istouch)
        _\(key).hovered = _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h)
    end
""" }

    private static func labelFuncs(_ key: String, mod: String, e: UIElement) -> String { """
-- Label: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    love.graphics.setColor(e.style.text)
    _fmPrintf(e, e.label, e.x, e.y + (e.h - e.style.fontSize)*0.5, e.w, "left")
end
function \(mod)._update_\(key)(dt) end
function \(mod)._mp_\(key)(x,y,btn) end
function \(mod)._mr_\(key)(x,y,btn) end
function \(mod)._mm_\(key)(x,y,dx,dy,istouch) end
""" }

    private static func sliderFuncs(_ key: String, mod: String) -> String { """
-- Slider: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    local tx, ty, tw, th = e.x, e.y + e.h*0.5 - 3, e.w, 6
    _drawBox(tx, ty, tw, th, 3, e.style.track, e.style.border, 0)
    local t = (e.value - e.minValue) / math.max(0.001, e.maxValue - e.minValue)
    local thumbX = e.x + t * e.w
    local sz = e.style.thumbSz * 0.5
    love.graphics.setColor(e.hovered and e.style.hover or e.style.thumb)
    love.graphics.circle("fill", thumbX, e.y + e.h*0.5, sz)
    love.graphics.setColor(e.style.border)
    love.graphics.setLineWidth(1)
    love.graphics.circle("line", thumbX, e.y + e.h*0.5, sz)
    love.graphics.setColor(e.style.text)
    _fmPrint(e, string.format("%.2f", e.value), e.x + e.w + 6, e.y + (e.h - e.style.fontSize)*0.5)
end
function \(mod)._update_\(key)(dt)
    if _\(key).dragging then
        local mx = love.mouse.getX()
        local t  = math.max(0, math.min(1, (mx - _\(key).x) / _\(key).w))
        local prev = _\(key).value
        _\(key).value = _\(key).minValue + t * (_\(key).maxValue - _\(key).minValue)
        if _\(key).value ~= prev and \(mod).on.\(key) then \(mod).on.\(key)(_\(key)) end
    end
end
function \(mod)._mp_\(key)(x,y,btn)
    if btn==1 and _inRect(x,y,_\(key).x,_\(key).y-8,_\(key).w,_\(key).h+16) and _\(key).enabled then
        _\(key).dragging=true
    end
end
function \(mod)._mr_\(key)(x,y,btn)
    if btn==1 then _\(key).dragging=false end
end
function \(mod)._mm_\(key)(x,y,dx,dy,istouch)
    _\(key).hovered = _inRect(x,y,_\(key).x,_\(key).y-8,_\(key).w,_\(key).h+16)
end
""" }

    private static func progressFuncs(_ key: String, mod: String) -> String { """
-- Progress Bar: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    _drawBox(e.x, e.y, e.w, e.h, e.style.radius, e.style.track, e.style.border, e.style.bw)
    local t = (e.value - e.minValue) / math.max(0.001, e.maxValue - e.minValue)
    local fillW = math.max(0, t * (e.w - 2))
    if fillW > 0 then
        love.graphics.setColor(e.style.accent)
        love.graphics.rectangle("fill", e.x+1, e.y+1, fillW, e.h-2, e.style.radius)
    end
    love.graphics.setColor(e.style.text)
    _fmPrintf(e, string.format("%d%%", math.floor(t*100)), e.x, e.y+(e.h-e.style.fontSize)*0.5, e.w, "center")
end
function \(mod)._update_\(key)(dt) end
function \(mod)._mp_\(key)(x,y,btn) end
function \(mod)._mr_\(key)(x,y,btn) end
function \(mod)._mm_\(key)(x,y,dx,dy,istouch) end
""" }

    private static func checkboxFuncs(_ key: String, mod: String) -> String { """
-- Checkbox: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    local sz = e.h - 4
    local bx, by = e.x + 2, e.y + 2
    _drawBox(bx, by, sz, sz, 4, e.checked and e.style.accent or e.style.bg, e.style.border, e.style.bw)
    if e.checked then
        love.graphics.setColor(e.style.text)
        love.graphics.setLineWidth(2)
        love.graphics.line(bx+4, by+sz*0.5, bx+sz*0.35, by+sz-4, bx+sz-4, by+4)
    end
    love.graphics.setColor(e.hovered and e.style.hover or e.style.text)
    _fmPrint(e, e.label, e.x + sz + 10, e.y + (e.h - e.style.fontSize)*0.5)
end
function \(mod)._update_\(key)(dt) end
function \(mod)._mp_\(key)(x,y,btn)
    if btn==1 and _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h) and _\(key).enabled then
        _\(key).checked = not _\(key).checked
        if \(mod).on.\(key) then \(mod).on.\(key)(_\(key)) end
    end
end
function \(mod)._mr_\(key)(x,y,btn) end
function \(mod)._mm_\(key)(x,y,dx,dy,istouch)
    _\(key).hovered = _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h)
end
""" }

    private static func radioFuncs(_ key: String, mod: String) -> String { """
-- Radio Button: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    local r = (e.h - 4) * 0.5
    local cx, cy = e.x + r + 2, e.y + e.h*0.5
    love.graphics.setColor(e.checked and e.style.accent or e.style.bg)
    love.graphics.circle("fill", cx, cy, r)
    love.graphics.setColor(e.style.border)
    love.graphics.setLineWidth(e.style.bw)
    love.graphics.circle("line", cx, cy, r)
    if e.checked then
        love.graphics.setColor(e.style.text)
        love.graphics.circle("fill", cx, cy, r*0.45)
    end
    love.graphics.setColor(e.style.text)
    _fmPrint(e, e.label, e.x + r*2 + 10, e.y + (e.h - e.style.fontSize)*0.5)
end
function \(mod)._update_\(key)(dt) end
function \(mod)._mp_\(key)(x,y,btn)
    if btn==1 and _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h) and _\(key).enabled then
        _\(key).checked = true
        if \(mod).on.\(key) then \(mod).on.\(key)(_\(key)) end
    end
end
function \(mod)._mr_\(key)(x,y,btn) end
function \(mod)._mm_\(key)(x,y,dx,dy,istouch)
    _\(key).hovered = _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h)
end
""" }

    private static func panelFuncs(_ key: String, mod: String, e: UIElement) -> String { """
-- Panel: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    _drawBox(e.x, e.y, e.w, e.h, e.style.radius, e.style.bg, e.style.border, e.style.bw)
    love.graphics.setColor(e.style.text)
    _fmPrintf(e, e.label, e.x + e.style.padding, e.y + e.style.padding, e.w - e.style.padding*2, "left")
end
function \(mod)._update_\(key)(dt) end
function \(mod)._mp_\(key)(x,y,btn) end
function \(mod)._mr_\(key)(x,y,btn) end
function \(mod)._mm_\(key)(x,y,dx,dy,istouch) end
""" }

    private static func textInputFuncs(_ key: String, mod: String) -> String { """
-- Text Input: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    local bg = e.focused and e.style.hover or e.style.bg
    _drawBox(e.x, e.y, e.w, e.h, e.style.radius, bg, e.focused and e.style.accent or e.style.border, e.focused and 2 or e.style.bw)
    local displayText = #e.text > 0 and e.text or e.placeholder
    love.graphics.setColor(#e.text > 0 and e.style.text or { e.style.text[1], e.style.text[2], e.style.text[3], 0.4 })
    _fmPrintf(e, displayText, e.x + e.style.padding, e.y + (e.h - e.style.fontSize)*0.5, e.w - e.style.padding*2, "left")
    if e.focused and math.floor(love.timer.getTime()*2)%2==0 then
        local _fm2 = _setElemFont(e)
        local tw = love.graphics.getFont():getWidth(e.text)
        _restoreElemFont(e, _fm2)
        love.graphics.setColor(e.style.text)
        love.graphics.setLineWidth(1)
        love.graphics.line(e.x+e.style.padding+tw+1, e.y+6, e.x+e.style.padding+tw+1, e.y+e.h-6)
    end
end
function \(mod)._update_\(key)(dt)
    if _\(key).focused and love.keyboard.isDown("backspace") then
        -- handled via keypressed, see love.keypressed hook
    end
end
function \(mod)._mp_\(key)(x,y,btn)
    if btn==1 then
        _\(key).focused = _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h) and _\(key).enabled
    end
end
function \(mod)._mr_\(key)(x,y,btn) end
function \(mod)._mm_\(key)(x,y,dx,dy,istouch)
    _\(key).hovered = _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h)
end
""" }

    private static func imageFuncs(_ key: String, mod: String) -> String { """
-- Image: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    if e.image then
        love.graphics.setColor(1,1,1,1)
        local iw, ih = e.image:getDimensions()
        love.graphics.draw(e.image, e.x, e.y, 0, e.w/iw, e.h/ih)
    else
        _drawBox(e.x, e.y, e.w, e.h, e.style.radius, e.style.bg, e.style.border, e.style.bw)
        love.graphics.setColor(e.style.text)
        love.graphics.printf("[ image ]", e.x, e.y+(e.h-e.style.fontSize)*0.5, e.w, "center")
    end
end
function \(mod)._update_\(key)(dt) end
function \(mod)._mp_\(key)(x,y,btn) end
function \(mod)._mr_\(key)(x,y,btn) end
function \(mod)._mm_\(key)(x,y,dx,dy,istouch) end
""" }

    private static func scrollBarFuncs(_ key: String, mod: String) -> String { """
-- Scroll Bar: \(key)
function \(mod)._draw_\(key)()
    local e = _\(key)
    _drawBox(e.x, e.y, e.w, e.h, 4, e.style.track, e.style.border, 0)
    local thumbH = math.max(20, e.h * 0.25)
    local travel = e.h - thumbH
    local thumbY = e.y + e.value * travel
    love.graphics.setColor(e.hovered and e.style.hover or e.style.thumb)
    love.graphics.rectangle("fill", e.x+2, thumbY, e.w-4, thumbH, 4)
end
function \(mod)._update_\(key)(dt)
    if _\(key).dragging then
        local my   = love.mouse.getY()
        local thumbH = math.max(20, _\(key).h * 0.25)
        local travel = _\(key).h - thumbH
        local prev = _\(key).value
        _\(key).value = math.max(0, math.min(1, (my - _\(key).y - thumbH*0.5) / travel))
        if _\(key).value ~= prev and \(mod).on.\(key) then \(mod).on.\(key)(_\(key)) end
    end
end
function \(mod)._mp_\(key)(x,y,btn)
    if btn==1 and _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h) and _\(key).enabled then
        _\(key).dragging=true
    end
end
function \(mod)._mr_\(key)(x,y,btn)
    if btn==1 then _\(key).dragging=false end
end
function \(mod)._mm_\(key)(x,y,dx,dy,istouch)
    _\(key).hovered = _inRect(x,y,_\(key).x,_\(key).y,_\(key).w,_\(key).h)
end
""" }

    // MARK: - Helpers

    private static func fmt(_ v: Double) -> String { String(format: "%.1f", v) }

    private static func blockOrComment(_ lines: [String], empty: String) -> String {
        lines.isEmpty ? "    -- \(empty)" : lines.joined(separator: "\n")
    }

    private static func textInputHandlerBody(config: UIBuilderConfig, mod: String) -> String {
        let textInputs = config.elements.filter { $0.type == .textInput }
        guard !textInputs.isEmpty else {
            return "    -- No text input widgets configured right now.\n    -- Keep this callback forwarded so future text fields work immediately."
        }

        return textInputs.map { e in
            let key = luaIdent(e.name)
            return """
    if _\(key).focused and _\(key).enabled then
        _\(key).text = _\(key).text .. t
        if \(mod).on.\(key) then \(mod).on.\(key)(_\(key)) end
    end
"""
        }.joined(separator: "\n")
    }

    private static func keyPressedHandlerBody(config: UIBuilderConfig, mod: String) -> String {
        let textInputs = config.elements.filter { $0.type == .textInput }
        guard !textInputs.isEmpty else {
            return """
    -- No text inputs configured yet.
    -- This callback is still generated so you can forward keyboard events now
    -- and add text fields later without touching main.lua again.
"""
        }

        let inputBlocks = textInputs.map { e in
            let key = luaIdent(e.name)
            return """
    if _\(key).focused and _\(key).enabled then
        if key == "backspace" then
            local byteoffset = utf8.offset(_\(key).text, -1)
            if byteoffset then
                _\(key).text = string.sub(_\(key).text, 1, byteoffset - 1)
            else
                _\(key).text = ""
            end
            if \(mod).on.\(key) then \(mod).on.\(key)(_\(key)) end
            return
        elseif key == "escape" then
            _\(key).focused = false
            return
        end
    end
"""
        }.joined(separator: "\n")

        return """
    -- Generated keyboard handling for focused text inputs.
\(inputBlocks)
"""
    }

    private static func wheelMovedHandlerBody(config: UIBuilderConfig, mod: String) -> String {
        let scrollbars = config.elements.filter { $0.type == .scrollBar }
        guard !scrollbars.isEmpty else {
            return """
    -- No scroll bars configured.
    -- Forwarding wheel input is still recommended for future UI growth.
"""
        }

        let blocks = scrollbars.map { e in
            let key = luaIdent(e.name)
            return """
    if _\(key).hovered and _\(key).enabled then
        local prev = _\(key).value
        _\(key).value = math.max(0, math.min(1, _\(key).value - dy * 0.08))
        if _\(key).value ~= prev and \(mod).on.\(key) then
            \(mod).on.\(key)(_\(key))
        end
    end
"""
        }.joined(separator: "\n")

        return """
    -- Mouse wheel updates hovered scrollbars.
\(blocks)
"""
    }

    private static func luaQuoted(_ string: String) -> String {
        let escaped = string
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    static func luaIdent(_ name: String) -> String {
        let safe = name
            .components(separatedBy: CharacterSet.alphanumerics.union(.init(charactersIn: "_")).inverted)
            .joined(separator: "_")
            .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        let result = safe.isEmpty ? "element" : safe
        return result.first?.isNumber == true ? "_\(result)" : result
    }
}
